# Tuning

In [1]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score

import joblib
import os
import pandas as pd
import numpy as np
import optuna

from scipy import stats

from sklearn.model_selection import train_test_split, KFold, StratifiedKFold, \
StratifiedShuffleSplit, GridSearchCV, RandomizedSearchCV

from sklearn.linear_model import LinearRegression, LogisticRegression, Ridge, Lasso, ElasticNet,\
RidgeClassifier, LogisticRegressionCV

from lightgbm import LGBMClassifier, LGBMRegressor, early_stopping
from catboost import CatBoostClassifier, CatBoostRegressor, Pool

from optuna.integration import CatBoostPruningCallback

from sklearn.metrics import mean_absolute_error, mean_squared_error, f1_score, accuracy_score, \
roc_auc_score, classification_report, r2_score, precision_score, recall_score, \
log_loss, mean_squared_log_error

from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder

import matplotlib.pyplot as plt
import seaborn as sns
            
from tqdm import tqdm_notebook
from tqdm import tqdm

import warnings
warnings.filterwarnings("ignore")

import ipywidgets
from get_metrics import get_metrics_classification

RAND = 10
N_FOLDS = 5

In [2]:
# Загрузка моделей и датасетов

df_train =  pd.read_csv("df_train_lr.csv")
df_train_2 = pd.read_csv("df_train_2.csv")

model_Sex_F = joblib.load('model_Sex_F.pkl') #LR Sex_F
model_ADHD = joblib.load('model_ADHD.pkl') #LR ADHD
clf_1 = joblib.load('clf_1.pkl') #LightGBM ADHD
clf_2 = joblib.load('clf_2.pkl') #LightGBM Sex_F
clf_c_1 = joblib.load('clf_c_1.pkl') #CatBoost ADHD
clf_c_2 = joblib.load('clf_c_2.pkl') #CatBoost Sex_F

In [3]:
# Разделение для логистической регрессии 
X = df_train.drop(['ADHD_Outcome', 'Sex_F'], axis=1)
y_ADHD = df_train['ADHD_Outcome'].values
y_Sex_F = df_train['Sex_F'].values

X_train_1_ADHD, X_test_1_ADHD, y_train_1_ADHD, y_test_1_ADHD = train_test_split(X,
                                                    y_ADHD,
                                                    test_size=0.2,
                                                    random_state=RAND,
                                                    stratify=y_ADHD)

X_train_1_ADHD_, X_val_1_ADHD, y_train_1_ADHD_, y_val_1_ADHD = train_test_split(X_train_1_ADHD,
                                                    y_train_1_ADHD,
                                                    test_size=0.16,
                                                    shuffle=True,
                                                    random_state=RAND)

X_train_1_Sex_F, X_test_1_Sex_F, y_train_1_Sex_F, y_test_1_Sex_F = train_test_split(X,
                                                    y_Sex_F,
                                                    test_size=0.2,
                                                    random_state=RAND,
                                                    stratify=y_Sex_F)


X_train_1_Sex_F_, X_val_1_Sex_F, y_train_1_Sex_F_, y_val_1_Sex_F = train_test_split(X_train_1_Sex_F,
                                                    y_train_1_Sex_F,
                                                    test_size=0.16,
                                                    shuffle=True,
                                                    random_state=RAND)

In [4]:
# Разделение для бустингов
X_cat = df_train_2.drop(['ADHD_Outcome', 'Sex_F'], axis=1)
y_cat_ADHD = df_train_2['ADHD_Outcome']
y_cat_Sex_F = df_train_2['Sex_F']

X_train_ADHD, X_test_ADHD, y_train_ADHD, y_test_ADHD = train_test_split(X_cat,
                                                    y_cat_ADHD,
                                                    test_size=0.2,
                                                    shuffle=True,
                                                    random_state=RAND)

X_train_ADHD_, X_val_ADHD, y_train_ADHD_, y_val_ADHD = train_test_split(X_train_ADHD,
                                                    y_train_ADHD,
                                                    test_size=0.16,
                                                    shuffle=True,
                                                    random_state=RAND)

X_train_Sex_F, X_test_Sex_F, y_train_Sex_F, y_test_Sex_F = train_test_split(X_cat,
                                                    y_cat_Sex_F,
                                                    test_size=0.2,
                                                    shuffle=True,
                                                    random_state=RAND)

X_train_Sex_F_, X_val_Sex_F, y_train_Sex_F_, y_val_Sex_F = train_test_split(X_train_Sex_F,
                                                    y_train_Sex_F,
                                                    test_size=0.16,
                                                    shuffle=True,
                                                    random_state=RAND)

In [5]:
# Предсказывание для лоогистической регрессии
y_prob_ADHD_train = model_ADHD.predict_proba(X_val_1_ADHD)
y_pred_ADHD_train = model_ADHD.predict(X_val_1_ADHD)

y_prob_Sex_F_train = model_Sex_F.predict_proba(X_val_1_Sex_F)
y_pred_Sex_F_train = model_Sex_F.predict(X_val_1_Sex_F)

# Предсказывание для LightGBM
y_pred_1 = clf_1.predict(X_val_ADHD)
y_pred_2 = clf_2.predict(X_val_Sex_F)

# Предсказывание CatBoost
y_pred_c_1 = clf_c_1.predict(X_val_ADHD)
y_pred_c_2 = clf_c_2.predict(X_val_Sex_F)

  File "C:\Users\User\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py", line 199, in _count_physical_cores
    cpu_info = subprocess.run(
               ^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\User\anaconda3\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

In [6]:
#Выведем метрики на Baseline для ADHD
metrics_ADHD = get_metrics_classification(y_val_1_ADHD,
                           y_pred_ADHD_train,
                           y_prob_ADHD_train,
                           name='LogisticRegression_Baseline_ADHD')
metrics_ADHD = pd.concat([metrics_ADHD,
    get_metrics_classification(y_test=y_val_ADHD,
                               y_pred=y_pred_1,
                               y_score=clf_1.predict_proba(X_val_ADHD),
                               name='LightGBM_eval_Baseline_ADHD')])
metrics_ADHD = pd.concat([metrics_ADHD,
    get_metrics_classification(y_test=y_val_ADHD,
                               y_pred=y_pred_c_1,
                               y_score=clf_c_1.predict_proba(X_val_ADHD),
                               name='CatBoost_eval_Baseline_ADHD')])

round(metrics_ADHD.set_index('model'), 3)

,Accuracy,ROC_AUC,Precision,Recall,f1,Logloss
model,,,,,,
LogisticRegression_Baseline_ADHD,0.636,0.585,0.727,0.762,0.744,1.400
LightGBM_eval_Baseline_ADHD,0.702,0.788,0.698,0.926,0.796,0.565
CatBoost_eval_Baseline_ADHD,0.689,0.743,0.682,0.947,0.793,0.633

In [7]:
#Выведем метрики на Baseline для Sex_F
metrics_Sex_F = get_metrics_classification(y_val_1_Sex_F,
                                     y_pred_Sex_F_train,
                                     y_prob_Sex_F_train,
                                     name='LogisticRegression_Baseline_Sex_F')
metrics_Sex_F = pd.concat([metrics_Sex_F,
    get_metrics_classification(y_test=y_val_Sex_F,
                               y_pred=y_pred_2,
                               y_score=clf_2.predict_proba(X_val_Sex_F),
                               name='LightGBM_Baseline_Sex_F')])
metrics_Sex_F = pd.concat([metrics_Sex_F,
    get_metrics_classification(y_test=y_val_Sex_F,
                               y_pred=y_pred_c_2,
                               y_score=clf_c_2.predict_proba(X_val_Sex_F),
                               name='CatBoost_Baseline_Sex_F')])

round(metrics_Sex_F.set_index('model'), 3)

,Accuracy,ROC_AUC,Precision,Recall,f1,Logloss
model,,,,,,
LogisticRegression_Baseline_Sex_F,0.709,0.724,0.541,0.426,0.476,0.990
LightGBM_Baseline_Sex_F,0.669,0.723,0.625,0.185,0.286,0.643
CatBoost_Baseline_Sex_F,0.675,0.756,0.778,0.130,0.222,0.573

# Optuna

In [8]:
def objective_lr(trial, X, y, N_FOLDS, random_state):
    #Гиперпараметры для подбора
    lr_params = {
        "C": trial.suggest_float('C', 1e-4, 10.0, log=True),
        "penalty": trial.suggest_categorical('penalty', ['l1', 'l2']),
        "solver": trial.suggest_categorical('solver', ['liblinear', 'saga'])
        } 
    #Кросс-валидация
    cv = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=random_state)
    cv_predicts = np.empty(N_FOLDS)

    for idx, (train_idx, test_idx) in enumerate(cv.split(X, y)):

        X_train_, X_val = X.iloc[train_idx], X.iloc[test_idx]
        y_train_, y_val = y[train_idx], y[test_idx]
        
        # Модель LogisticRegression    
        model = LogisticRegression(**lr_params)
        model.fit(X_train_,
                  y_train_,
                 )  
        preds = model.predict(X_val)
        cv_predicts[idx] = roc_auc_score(y_val, preds)

    return np.mean(cv_predicts)

In [9]:
#Сравнение по метрике ROC-AUC модель LR baseline и optune 
def evaluate_cv_lr(model, X, y, random_state, N_FOLDS = 5):

    cv_scores = []

    cv = StratifiedKFold(
        n_splits=N_FOLDS,
        shuffle=True,
        random_state=random_state
    )
    
    for fold, (train_idx, val_idx) in enumerate(cv.split(X, y), 1):

        X_train_ = X.iloc[train_idx]
        X_val_ = X.iloc[val_idx]

        y_train_ = y[train_idx]
        y_val_ = y[val_idx]

        model.fit(
            X_train_,
            y_train_,
        )

        y_pred_proba = model.predict_proba(X_val_)[:, 1]

        score = roc_auc_score(y_val_, y_pred_proba)
        cv_scores.append(score)
        print(f"Fold {fold}: ROC-AUC:{score:.4f}")
    print(f"\nMean ROC-AUC: {np.mean(cv_scores):.4f}")
    print(f"Std: {np.std(cv_scores):.4f}")

    return np.mean(cv_scores), np.std(cv_scores)

In [10]:
def objective_lgb(trial, X, y, N_FOLDS, random_state):
    #Гиперпараметры для подбора
    lgb_params = {
        "num_leaves": trial.suggest_int("num_leaves", 20, 100),
        "max_depth": trial.suggest_int("max_depth", 3, 6),
        "max_bin": trial.suggest_int("max_bin", 128, 255),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
        "n_estimators": trial.suggest_int("n_estimators", 200, 2000),
        "min_child_samples": trial.suggest_int("min_child_samples", 10, 100),
        "subsample": trial.suggest_float("subsample", 0.8, 0.9),
        "reg_alpha": trial.suggest_float("reg_alpha", 0.01, 1.0, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 0.01, 1.0, log=True),
        "random_state": RAND,
        "n_jobs": None,
        "verbosity": -1
    }

    #Кросс-валидация
    cv = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=random_state)
    cv_predicts = []

    for idx, (train_idx, test_idx) in enumerate(cv.split(X, y)):
        X_train_, X_val = X.iloc[train_idx], X.iloc[test_idx]
        y_train_, y_val = y.iloc[train_idx], y.iloc[test_idx]

        # Модель LightGBM
        model = LGBMClassifier(**lgb_params)
        pruning_callback = optuna.integration.LightGBMPruningCallback(
            trial, "auc")

        model.fit(
            X_train_,
            y_train_,
            eval_set=[(X_val, y_val)],
            eval_metric="auc",
            callbacks=[
                       early_stopping(stopping_rounds=100)]
        )

        y_pred_proba = model.predict_proba(X_val)[:, 1]
        cv_predict = roc_auc_score(y_val, y_pred_proba)
        cv_predicts.append(cv_predict)

    return np.mean(cv_predicts)

In [11]:
#Сравнение по метрике ROC-AUC модель LightGBM baseline и optune 
def evaluate_cv_lgb(model, X, y, random_state, N_FOLDS = 5):

    cv_scores = []

    cv = StratifiedKFold(
        n_splits=N_FOLDS,
        shuffle=True,
        random_state=random_state
    )
    
    for fold, (train_idx, val_idx) in enumerate(cv.split(X, y), 1):

        X_train_ = X.iloc[train_idx]
        X_val_ = X.iloc[val_idx]

        y_train_ = y.iloc[train_idx]
        y_val_ = y.iloc[val_idx]

        model.fit(
            X_train_,
            y_train_,
            eval_set=[(X_val_, y_val_)],
            eval_metric="auc",
            callbacks=[
                       early_stopping(stopping_rounds=100)
                       ]
        )
        
        y_pred_proba = model.predict_proba(X_val_)[:, 1]

        score = roc_auc_score(y_val_, y_pred_proba)
        cv_scores.append(score)
        print(f"Fold {fold}: ROC-AUC:{score:.4f}")
    print(f"\nMean ROC-AUC: {np.mean(cv_scores):.4f}")
    print(f"Std: {np.std(cv_scores):.4f}")

    return np.mean(cv_scores), np.std(cv_scores)

In [12]:
def objective_catboost(trial, X, y, N_FOLDS, random_state):
    #Гиперпараметры для подбора
    cb_params = {
        "iterations": trial.suggest_int("iterations", 100, 1500),
        "learning_rate": trial.suggest_float("learning_rate", 0.02, 0.2, log=True),
        "depth": trial.suggest_int("depth", 4, 6),
        "l2_leaf_reg": trial.suggest_float("l2_leaf_reg", 1, 10),
        "border_count": trial.suggest_int("border_count", 32, 128),
        "loss_function": "Logloss",
        "eval_metric": "AUC",
        "random_state": random_state,
        "task_type": "CPU",
        "verbose": 100,
        "allow_writing_files": False,
        "od_type": "Iter",
        "od_wait": 30,  # ранняя остановка
    }
    #Кросс-валидация
    cv_scores = []

    cv = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=random_state)
    
    for train_idx, val_idx in cv.split(X, y):

        X_train_, X_val = X.iloc[train_idx], X.iloc[val_idx]
        y_train_, y_val = y.iloc[train_idx], y.iloc[val_idx]

        # Модель CatBoostClassifier         
        model = CatBoostClassifier(**cb_params)
        model.fit(
            X_train_, y_train_,
            eval_set = (X_val, y_val),
            use_best_model = True,
            early_stopping_rounds=100
        )
        
        y_pred_proba = model.predict_proba(X_val)[:, 1]
        score = roc_auc_score(y_val, y_pred_proba)
        cv_scores.append(score)

    return np.mean(cv_scores)

In [13]:
#Сравнение по метрике ROC-AUC модель CatBoost baseline и optune 
def evaluate_cv_catboost(model, X, y, random_state, N_FOLDS = 5):

    cv_scores = []

    cv = StratifiedKFold(
        n_splits=N_FOLDS,
        shuffle=True,
        random_state=random_state
    )
    X = pd.DataFrame(X)
    y = pd.DataFrame(y)
    for fold, (train_idx, val_idx) in enumerate(cv.split(X, y), 1):

        X_train_ = X.iloc[train_idx]
        X_val_ = X.iloc[val_idx]

        y_train_ = y.iloc[train_idx]
        y_val_ = y.iloc[val_idx]

        model.fit(
            X_train_,
            y_train_,
            eval_set=(X_val_, y_val_),
            use_best_model=True,
            early_stopping_rounds=100,
            verbose = False
        )

        y_pred_proba = model.predict_proba(X_val_)[:, 1]

        score = roc_auc_score(y_val_, y_pred_proba)
        cv_scores.append(score)
        print(f"Fold {fold}: ROC-AUC:{score:.4f}")
    print(f"\nMean ROC-AUC: {np.mean(cv_scores):.4f}")
    print(f"Std: {np.std(cv_scores):.4f}")

    return np.mean(cv_scores), np.std(cv_scores)

In [14]:
#Нахождение гиперпараметров LR для таргета ADHD

study = optuna.create_study(direction="maximize", study_name="LR_ADHD")
func = lambda trial: objective_lr(
    trial, X_train_1_ADHD_, y_train_1_ADHD_, N_FOLDS=N_FOLDS, random_state=RAND)
optuna.logging.set_verbosity(optuna.logging.WARNING)
study.optimize(func, n_trials=30, show_progress_bar=True)

study.best_params

In [15]:
#Лучшие параметры для LR ADHD 
best_params_lr_ADHD = {'C': 0.00031170923197518425, 'penalty': 'l2', 'solver': 'liblinear'}  #ROC_AUC 0.578468

In [16]:
clf_ADHD_lr = LogisticRegression(**best_params_lr_ADHD)

clf_ADHD_lr.fit(X_train_1_ADHD_,
        y_train_1_ADHD_
        )

y_pred_ADHD_lr = clf_ADHD_lr.predict(X_val_1_ADHD)

In [17]:
metrics_optuna_ADHD = get_metrics_classification(y_test=y_val_1_ADHD,
                               y_pred=y_pred_ADHD_lr,
                               y_score=clf_ADHD_lr.predict_proba(X_val_1_ADHD),
                               name='LogisticRegression_Optuna_ADHD')

metrics_optuna_ADHD

,model,Accuracy,ROC_AUC,Precision,Recall,f1,Logloss
0,LogisticRegression_Optuna_ADHD,0.483444,0.578468,0.721311,0.419048,0.53012,0.739364

In [18]:
metrics_ADHD

,model,Accuracy,ROC_AUC,Precision,Recall,f1,Logloss
0,LogisticRegression_Baseline_ADHD,0.635762,0.584679,0.727273,0.761905,0.744186,1.399807
0,LightGBM_eval_Baseline_ADHD,0.701987,0.787970,0.698413,0.926316,0.796380,0.564567
0,CatBoost_eval_Baseline_ADHD,0.688742,0.743233,0.681818,0.947368,0.792952,0.633315

In [19]:
#На валидационной выборке модель полученная с помощью Optune проигрывает по метрикам, для точности проверю на 5 фолдах

In [20]:
#Значения на 5 фолдах для baseline LR для ADHD
ADHD_base_lr_mean, ADHD_base_lr_std = evaluate_cv_lr(
    model_ADHD,
    X_train_1_ADHD_,
    y_train_1_ADHD_,
    RAND)

Fold 1: ROC-AUC:0.5800
Fold 2: ROC-AUC:0.5804
Fold 3: ROC-AUC:0.5083
Fold 4: ROC-AUC:0.5687
Fold 5: ROC-AUC:0.6056

Mean ROC-AUC: 0.5686
Std: 0.0325

In [21]:
#Значения на 5 фолдах для opune LR для ADHD
ADHD_optune_lr_mean, ADHD_optune_lr_std = evaluate_cv_lr(
    clf_ADHD_lr,
    X_train_1_ADHD_,
    y_train_1_ADHD_,
    RAND)

Fold 1: ROC-AUC:0.5752
Fold 2: ROC-AUC:0.6034
Fold 3: ROC-AUC:0.5317
Fold 4: ROC-AUC:0.5607
Fold 5: ROC-AUC:0.6061

Mean ROC-AUC: 0.5754
Std: 0.0278

In [22]:
cv_models_ADHD = []
cv_models_ADHD.append({'Model_ADHD':'LogisticRegression_baseline_ADHD',
                               'Mean ROC-AUC':ADHD_base_lr_mean,
                               'Std': ADHD_base_lr_std})
cv_models_ADHD.append({'Model_ADHD':'LogisticRegression_optune_ADHD',
                               'Mean ROC-AUC':ADHD_optune_lr_mean,
                               'Std':ADHD_optune_lr_std})
cv_models_ADHD_df = pd.DataFrame(cv_models_ADHD)
round(cv_models_ADHD_df.set_index('Model_ADHD'), 3)

                                  Mean ROC-AUC    Std
Model_ADHD
LogisticRegression_baseline_ADHD         0.569  0.032
LogisticRegression_optune_ADHD           0.575  0.028

In [23]:
#На 5 фолдах уже можно увидеть, что метрика ROC-AUC модели LR для ADHD полученная через Optune выше на 0.5754 - 0.5686 = 0.0068

study_lr_F = optuna.create_study(direction="maximize", study_name="LR_SF")
func = lambda trial: objective_lr(
    trial, X_train_1_Sex_F_, y_train_1_Sex_F_, N_FOLDS=N_FOLDS, random_state=RAND)
optuna.logging.set_verbosity(optuna.logging.WARNING)
study_lr_F.optimize(func, n_trials=30, show_progress_bar=True)

study_lr_F.best_params

In [24]:
#Лучшие параметры для LR для Sex_F на 04.09
best_params_lr_Sex_f = {'C': 0.0004360436996760946, 'penalty': 'l2', 'solver': 'liblinear'}

In [25]:
clf_Sex_F_lr = LogisticRegression(**best_params_lr_Sex_f)

clf_Sex_F_lr.fit(X_train_Sex_F_,
        y_train_Sex_F_,
        )

y_pred_Sex_F_lr = clf_Sex_F_lr.predict(X_val_Sex_F)

In [26]:
metrics_optuna_Sex_F = get_metrics_classification(y_test=y_val_Sex_F,
                               y_pred=y_pred_Sex_F_lr,
                               y_score=clf_Sex_F_lr.predict_proba(X_val_Sex_F),
                               name='LogisticRegression_Optuna_Sex_F')

metrics_optuna_Sex_F

,model,Accuracy,ROC_AUC,Precision,Recall,f1,Logloss
0,LogisticRegression_Optuna_Sex_F,0.642384,0.724895,0.0,0.0,0.0,0.616547

In [27]:
metrics_Sex_F

,model,Accuracy,ROC_AUC,Precision,Recall,f1,Logloss
0,LogisticRegression_Baseline_Sex_F,0.708609,0.723813,0.540541,0.425532,0.476190,0.990092
0,LightGBM_Baseline_Sex_F,0.668874,0.723368,0.625000,0.185185,0.285714,0.642981
0,CatBoost_Baseline_Sex_F,0.675497,0.756396,0.777778,0.129630,0.222222,0.572879

In [28]:
#Значения на 5 фолдах для baseline LR для Sex_F
Sex_F_base_lr_mean, Sex_F_base_lr_std = evaluate_cv_lr(
    model_Sex_F,
    X_train_1_Sex_F_,
    y_train_1_Sex_F_,
    RAND)

Fold 1: ROC-AUC:0.7852
Fold 2: ROC-AUC:0.6955
Fold 3: ROC-AUC:0.7908
Fold 4: ROC-AUC:0.7575
Fold 5: ROC-AUC:0.7092

Mean ROC-AUC: 0.7476
Std: 0.0389

In [29]:
#Значения на 5 фолдах для optune LR для Sex_F
Sex_F_optune_lr_mean, Sex_F_optune_lr_std = evaluate_cv_lr(
    clf_Sex_F_lr,
    X_train_1_Sex_F_,
    y_train_1_Sex_F_,
    RAND)

Fold 1: ROC-AUC:0.7711
Fold 2: ROC-AUC:0.7013
Fold 3: ROC-AUC:0.7751
Fold 4: ROC-AUC:0.7573
Fold 5: ROC-AUC:0.7133

Mean ROC-AUC: 0.7436
Std: 0.0305

In [30]:
cv_models_Sex_F = []
cv_models_Sex_F.append({'Model_Sex_F':'LogisticRegression_baseline_Sex_F',
                               'Mean ROC-AUC':Sex_F_base_lr_mean,
                               'Std': Sex_F_base_lr_std})
cv_models_Sex_F.append({'Model_Sex_F':'LogisticRegression_optune_Sex_F',
                               'Mean ROC-AUC':Sex_F_optune_lr_mean,
                               'Std':Sex_F_optune_lr_std})
cv_models_Sex_F_df = pd.DataFrame(cv_models_Sex_F)
round(cv_models_Sex_F_df.set_index('Model_Sex_F'), 3)

                                   Mean ROC-AUC    Std
Model_Sex_F
LogisticRegression_baseline_Sex_F         0.748  0.039
LogisticRegression_optune_Sex_F           0.744  0.030

In [31]:
#Для таргета Sex_F логистическая регрессия на бейзлайне сработала лучше по метрике ROC-AUC на 0.004

study_lg_A = optuna.create_study(direction="maximize", study_name="LGB_ADHD")
func = lambda trial: objective_lgb(
    trial, X_train_ADHD_, y_train_ADHD_, N_FOLDS=N_FOLDS, random_state=RAND)
optuna.logging.set_verbosity(optuna.logging.WARNING)
study_lg_A.optimize(func, n_trials=30, show_progress_bar=True)

study_lg_A.best_params

In [32]:
#лучшие параметры для ADHD для LGBM #ROC AUC 0.733 на пяти фолдах 0.6925 0.7533
best_params_ADHD_lgb = {'num_leaves': 27,
 'max_depth': 6,
 'max_bin': 142,
 'learning_rate': 0.015367920082427804,
 'n_estimators': 1807,
 'min_child_samples': 15,
 'subsample': 0.8446879181304909,
 'reg_alpha': 0.022770476384198494,
 'reg_lambda': 0.121697317902343}

In [33]:
clf_ADHD_lgb = LGBMClassifier(**best_params_ADHD_lgb, verbosity = -1)
eval_set = [(X_val_ADHD, y_val_ADHD)]

clf_ADHD_lgb.fit(X_train_ADHD_,
        y_train_ADHD_,
        eval_set=eval_set,
        eval_metric ='auc'
        )

y_pred_ADHD_lgb = clf_ADHD_lgb.predict(X_val_ADHD)

In [34]:
metrics_optuna_ADHD = pd.concat([metrics_optuna_ADHD,
    get_metrics_classification(y_test=y_val_ADHD,
                               y_pred=y_pred_ADHD_lgb,
                               y_score=clf_ADHD_lgb.predict_proba(X_val_ADHD),
                               name='LightGBM_Optuna_ADHD')])

round(metrics_optuna_ADHD.set_index('model'), 3)

,Accuracy,ROC_AUC,Precision,Recall,f1,Logloss
model,,,,,,
LogisticRegression_Optuna_ADHD,0.483,0.578,0.721,0.419,0.53,0.739
LightGBM_Optuna_ADHD,0.689,0.733,0.671,0.989,0.80,0.991

In [35]:
#Проверим на 5 фолдах LightGBM и сравним baseline и optune для ADHD

In [36]:
#Значения на 5 фолдах для baseline LightGBM для ADHD
ADHD_base_lgbm_mean, ADHD_base_lgbm_std = evaluate_cv_lgb(
    clf_1,
    X_train_ADHD_,
    y_train_ADHD_,
    RAND)

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[21]	valid_0's auc: 0.739205
Fold 1: ROC-AUC:0.7392
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[7]	valid_0's auc: 0.733333
Fold 2: ROC-AUC:0.7333
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[27]	valid_0's auc: 0.710606
Fold 3: ROC-AUC:0.7106
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[88]	valid_0's auc: 0.764015
Fold 4: ROC-AUC:0.7640
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[44]	valid_0's auc: 0.752294
Fold 5: ROC-AUC:0.7523

Mean ROC-AUC: 0.7399
Std: 0.0181

In [37]:
#Значения на 5 фолдах для opune LightGBM для ADHD
ADHD_optune_lgbm_mean, ADHD_optune_lgbm_std = evaluate_cv_lgb(
    clf_ADHD_lgb,
    X_train_ADHD_,
    y_train_ADHD_,
    RAND)

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[102]	valid_0's auc: 0.803977	valid_0's binary_logloss: 0.524128
Fold 1: ROC-AUC:0.8040
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[145]	valid_0's auc: 0.706439	valid_0's binary_logloss: 0.570153
Fold 2: ROC-AUC:0.7064
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[106]	valid_0's auc: 0.792235	valid_0's binary_logloss: 0.523338
Fold 3: ROC-AUC:0.7922
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[204]	valid_0's auc: 0.757197	valid_0's binary_logloss: 0.52833
Fold 4: ROC-AUC:0.7572
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[119]	valid_0's auc: 0.706422	valid_0's binary_logloss: 0.558191
Fold 5: ROC-AUC:0.7064

Mean ROC-AUC: 0.7533
Std: 0.0412

In [38]:
cv_models_ADHD.append({'Model_ADHD':'LightGBM_baseline_ADHD',
                               'Mean ROC-AUC':ADHD_base_lgbm_mean,
                               'Std': ADHD_base_lgbm_std})
cv_models_ADHD.append({'Model_ADHD':'LightGBM_optune_ADHD',
                               'Mean ROC-AUC':ADHD_optune_lgbm_mean,
                               'Std':ADHD_optune_lgbm_std})
cv_models_ADHD_df = pd.DataFrame(cv_models_ADHD)
round(cv_models_ADHD_df.set_index('Model_ADHD'), 3)

                                  Mean ROC-AUC    Std
Model_ADHD
LogisticRegression_baseline_ADHD         0.569  0.032
LogisticRegression_optune_ADHD           0.575  0.028
LightGBM_baseline_ADHD                   0.740  0.018
LightGBM_optune_ADHD                     0.753  0.041

In [39]:
metrics_optuna_ADHD = pd.concat([metrics_optuna_ADHD,
    get_metrics_classification(y_test=y_val_ADHD,
                               y_pred=y_pred_ADHD_lgb,
                               y_score=clf_ADHD_lgb.predict_proba(X_val_ADHD),
                               name='LightGBM_Optuna_ADHD')])

round(metrics_optuna_ADHD.set_index('model'), 3)

,Accuracy,ROC_AUC,Precision,Recall,f1,Logloss
model,,,,,,
LogisticRegression_Optuna_ADHD,0.483,0.578,0.721,0.419,0.53,0.739
LightGBM_Optuna_ADHD,0.689,0.733,0.671,0.989,0.80,0.991
LightGBM_Optuna_ADHD,0.689,0.693,0.671,0.989,0.80,0.616

study_lg_S = optuna.create_study(direction="maximize", study_name="LGB_SF")
func = lambda trial: objective_lgb(
    trial, X_train_Sex_F_, y_train_Sex_F_, N_FOLDS=N_FOLDS, random_state=RAND)
optuna.logging.set_verbosity(optuna.logging.WARNING)
study_lg_S.optimize(func, n_trials=30, show_progress_bar=True)

study_lg_S.best_params

In [40]:
best_params_Sex_F_lgbm = {'boosting_type': 'gbdt',  #ROC_AUC 0.731195 на пяти фолдах 0.7051
 'num_leaves': 31,
 'max_depth': 7,
 'max_bin': 155,
 'learning_rate': 0.024226661799654204,
 'n_estimators': 1100,
 'min_child_samples': 80,
 'min_split_gain': 6.902201580309832,
 'subsample': 0.6168798865047278,
 'subsample_freq': 1,
 'colsample_bytree': 0.6141516293976439,
 'reg_alpha': 0.000628329986467489,
 'reg_lambda': 7.142504420569093e-08}

In [41]:
clf_Sex_F_lgb = LGBMClassifier(**best_params_Sex_F_lgbm, verbosity = -1)
eval_set = [(X_val_Sex_F, y_val_Sex_F)]

clf_Sex_F_lgb.fit(X_train_Sex_F_,
        y_train_Sex_F_,
        eval_set=eval_set,
        eval_metric ='auc'
        )

y_pred_Sex_F_lgb = clf_Sex_F_lgb.predict(X_val_Sex_F)

In [42]:
#Значения на 5 фолдах для baseline LightGBM для Sex_F
Sex_F_base_lgbm_mean, Sex_F_base_lgbm_std = evaluate_cv_lgb(
    clf_2,
    X_train_Sex_F_,
    y_train_Sex_F_,
    RAND)

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[54]	valid_0's auc: 0.645477
Fold 1: ROC-AUC:0.6455
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[93]	valid_0's auc: 0.626425
Fold 2: ROC-AUC:0.6264
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[100]	valid_0's auc: 0.68287
Fold 3: ROC-AUC:0.6829
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[69]	valid_0's auc: 0.68661
Fold 4: ROC-AUC:0.6866
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[46]	valid_0's auc: 0.689497
Fold 5: ROC-AUC:0.6895

Mean ROC-AUC: 0.6662
Std: 0.0255

In [43]:
#Значения на 5 фолдах для optune LightGBM для Sex_F
Sex_F_optune_lgbm_mean, Sex_F_optune_lgbm_std = evaluate_cv_lgb(
    clf_Sex_F_lgb,
    X_train_Sex_F_,
    y_train_Sex_F_,
    RAND)

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[355]	valid_0's auc: 0.678419	valid_0's binary_logloss: 0.594419
Fold 1: ROC-AUC:0.6779
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[390]	valid_0's auc: 0.698184	valid_0's binary_logloss: 0.587055
Fold 2: ROC-AUC:0.6968
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[254]	valid_0's auc: 0.774395	valid_0's binary_logloss: 0.560628
Fold 3: ROC-AUC:0.7744
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[152]	valid_0's auc: 0.70495	valid_0's binary_logloss: 0.602464
Fold 4: ROC-AUC:0.7050
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[131]	valid_0's auc: 0.671315	valid_0's binary_logloss: 0.610561
Fold 5: ROC-AUC:0.6713

Mean ROC-AUC: 0.7051
Std: 0.0368

In [44]:
cv_models_Sex_F.append({'Model_Sex_F':'LightGBM_baseline_Sex_F',
                               'Mean ROC-AUC':Sex_F_base_lgbm_mean,
                               'Std': Sex_F_base_lgbm_std})
cv_models_Sex_F.append({'Model_Sex_F':'LightGBM_optune_Sex_F',
                               'Mean ROC-AUC':Sex_F_optune_lgbm_mean,
                               'Std':Sex_F_optune_lgbm_std})
cv_models_Sex_F_df = pd.DataFrame(cv_models_Sex_F)
round(cv_models_Sex_F_df.set_index('Model_Sex_F'), 3)

                                   Mean ROC-AUC    Std
Model_Sex_F
LogisticRegression_baseline_Sex_F         0.748  0.039
LogisticRegression_optune_Sex_F           0.744  0.030
LightGBM_baseline_Sex_F                   0.666  0.025
LightGBM_optune_Sex_F                     0.705  0.037

In [45]:
metrics_optuna_Sex_F = pd.concat([metrics_optuna_Sex_F,
    get_metrics_classification(y_test=y_val_Sex_F,
                               y_pred=y_pred_Sex_F_lgb,
                               y_score=clf_Sex_F_lgb.predict_proba(X_val_Sex_F),
                               name='LightGBM_Optuna_Sex_F')])

metrics_optuna_Sex_F

,model,Accuracy,ROC_AUC,Precision,Recall,f1,Logloss
0,LogisticRegression_Optuna_Sex_F,0.642384,0.724895,0.000000,0.000000,0.0,0.616547
0,LightGBM_Optuna_Sex_F,0.701987,0.676212,0.714286,0.277778,0.4,0.613477

In [46]:
metrics_Sex_F

,model,Accuracy,ROC_AUC,Precision,Recall,f1,Logloss
0,LogisticRegression_Baseline_Sex_F,0.708609,0.723813,0.540541,0.425532,0.476190,0.990092
0,LightGBM_Baseline_Sex_F,0.668874,0.723368,0.625000,0.185185,0.285714,0.642981
0,CatBoost_Baseline_Sex_F,0.675497,0.756396,0.777778,0.129630,0.222222,0.572879

study_c_A = optuna.create_study(direction="maximize", study_name="Cat_ADHD")
func = lambda trial: objective_catboost(
    trial, X_train_ADHD_, y_train_ADHD_, N_FOLDS=N_FOLDS, random_state=RAND)
optuna.logging.set_verbosity(optuna.logging.WARNING)
study_c_A.optimize(func, n_trials=30, show_progress_bar=True)

study_c_A.best_params

In [47]:
#лучшие параметры для ADHD на CatBoost ROC AUC  0.6794
best_params_CB_ADHD = {'iterations': 927,
 'learning_rate': 0.023655836939172552,
 'depth': 4,
 'l2_leaf_reg': 3.655469435270644,
 'border_count': 86}

In [48]:
clf_ADHD_cb = CatBoostClassifier(**best_params_CB_ADHD)
eval_set = [(X_val_ADHD, y_val_ADHD)]

clf_ADHD_cb.fit(X_train_ADHD_,
        y_train_ADHD_,
        eval_set=eval_set,
        early_stopping_rounds=50,
        use_best_model=True,
        verbose = False
        )

y_pred_ADHD_cb = clf_ADHD_cb.predict(X_val_ADHD)

In [49]:
metrics_optuna_ADHD = pd.concat([metrics_optuna_ADHD,
    get_metrics_classification(y_test=y_val_ADHD,
                               y_pred=y_pred_ADHD_cb,
                               y_score=clf_ADHD_cb.predict_proba(X_val_ADHD),
                               name='CatBoost_Optuna_ADHD')])

round(metrics_optuna_ADHD.set_index('model'), 3)

,Accuracy,ROC_AUC,Precision,Recall,f1,Logloss
model,,,,,,
LogisticRegression_Optuna_ADHD,0.483,0.578,0.721,0.419,0.530,0.739
LightGBM_Optuna_ADHD,0.689,0.733,0.671,0.989,0.800,0.991
LightGBM_Optuna_ADHD,0.689,0.693,0.671,0.989,0.800,0.616
CatBoost_Optuna_ADHD,0.656,0.669,0.650,0.979,0.782,0.624

In [50]:
#Значения на 5 фолдах для baseline CatBoost для ADHD
ADHD_base_cb_mean, ADHD_base_cb = evaluate_cv_catboost(
    clf_c_1,
    X_train_ADHD_,
    y_train_ADHD_,
    RAND)

Fold 1: ROC-AUC:0.7170
Fold 2: ROC-AUC:0.6195
Fold 3: ROC-AUC:0.6278
Fold 4: ROC-AUC:0.7311
Fold 5: ROC-AUC:0.6066

Mean ROC-AUC: 0.6604
Std: 0.0526

In [51]:
#Значения на 5 фолдах для optune CatBoost для ADHD
ADHD_optune_cb_mean, ADHD_optune_cb_std = evaluate_cv_catboost(
    clf_ADHD_cb,
    X_train_ADHD_,
    y_train_ADHD_,
    RAND)

Fold 1: ROC-AUC:0.6970
Fold 2: ROC-AUC:0.6606
Fold 3: ROC-AUC:0.6794
Fold 4: ROC-AUC:0.7443
Fold 5: ROC-AUC:0.6156

Mean ROC-AUC: 0.6794
Std: 0.0423

In [52]:
cv_models_ADHD.append({'Model_ADHD':'CatBoost_baseline_ADHD',
                               'Mean ROC-AUC':ADHD_base_cb_mean,
                               'Std': ADHD_base_cb})
cv_models_ADHD.append({'Model_ADHD':'CatBoost_optune_ADHD',
                               'Mean ROC-AUC':ADHD_optune_cb_mean,
                               'Std':ADHD_optune_cb_std})
cv_models_ADHD_df = pd.DataFrame(cv_models_ADHD)
round(cv_models_ADHD_df.set_index('Model_ADHD'), 3)

                                  Mean ROC-AUC    Std
Model_ADHD
LogisticRegression_baseline_ADHD         0.569  0.032
LogisticRegression_optune_ADHD           0.575  0.028
LightGBM_baseline_ADHD                   0.740  0.018
LightGBM_optune_ADHD                     0.753  0.041
CatBoost_baseline_ADHD                   0.660  0.053
CatBoost_optune_ADHD                     0.679  0.042

In [53]:
metrics_ADHD

,model,Accuracy,ROC_AUC,Precision,Recall,f1,Logloss
0,LogisticRegression_Baseline_ADHD,0.635762,0.584679,0.727273,0.761905,0.744186,1.399807
0,LightGBM_eval_Baseline_ADHD,0.701987,0.787970,0.698413,0.926316,0.796380,0.564567
0,CatBoost_eval_Baseline_ADHD,0.688742,0.743233,0.681818,0.947368,0.792952,0.633315

study_c_F = optuna.create_study(direction="maximize", pruner=optuna.pruners.MedianPruner(),study_name="Cat_SF")
#'pruner = optuna.pruners.NopPruner()'
func = lambda trial: objective_catboost(
    trial, X_train_Sex_F_, y_train_Sex_F_, N_FOLDS=N_FOLDS, random_state=RAND)
optuna.logging.set_verbosity(optuna.logging.WARNING)
study_c_F.optimize(func, n_trials=40, show_progress_bar=True)

study_c_F.best_params

In [54]:
#лучшие параметры для Sex_F на CatBoost на 5 фолдах 0.6633
best_params_CB_Sex_F = {'iterations': 748,
 'learning_rate': 0.03813123817525072,
 'depth': 4,
 'l2_leaf_reg': 6.0621261420498325,
 'border_count': 86}

In [55]:
clf_Sex_F_cb = CatBoostClassifier(**best_params_CB_Sex_F)
eval_set = [(X_val_Sex_F, y_val_Sex_F)]

clf_Sex_F_cb.fit(X_train_Sex_F_,
        y_train_Sex_F_,
        eval_set=eval_set,
        verbose=False
        )

y_pred_Sex_F_cb = clf_Sex_F_cb.predict(X_val_Sex_F)

In [56]:
metrics_optuna_Sex_F = pd.concat([metrics_optuna_Sex_F,
    get_metrics_classification(y_test=y_val_Sex_F,
                               y_pred=y_pred_Sex_F_cb,
                               y_score=clf_Sex_F_cb.predict_proba(X_val_Sex_F),
                               name='CatBoost_Optuna_Sex_F')])

metrics_optuna_Sex_F

,model,Accuracy,ROC_AUC,Precision,Recall,f1,Logloss
0,LogisticRegression_Optuna_Sex_F,0.642384,0.724895,0.000000,0.000000,0.000000,0.616547
0,LightGBM_Optuna_Sex_F,0.701987,0.676212,0.714286,0.277778,0.400000,0.613477
0,CatBoost_Optuna_Sex_F,0.662252,0.733104,0.714286,0.092593,0.163934,0.590770

In [57]:
#Значения на 5 фолдах для baseline CatBoost для Sex_F
Sex_F_base_cb_mean, Sex_F_base_cb_std = evaluate_cv_catboost(
    clf_c_2,
    X_train_Sex_F_,
    y_train_Sex_F_,
    RAND)

Fold 1: ROC-AUC:0.6323
Fold 2: ROC-AUC:0.6920
Fold 3: ROC-AUC:0.7635
Fold 4: ROC-AUC:0.6471
Fold 5: ROC-AUC:0.6055

Mean ROC-AUC: 0.6681
Std: 0.0554

In [58]:
#Значения на 5 фолдах для optune CatBoost для Sex_F
Sex_F_optune_cb_mean, Sex_F_optune_cb_std = evaluate_cv_catboost(
    clf_Sex_F_cb,
    X_train_Sex_F_,
    y_train_Sex_F_,
    RAND)

Fold 1: ROC-AUC:0.6344
Fold 2: ROC-AUC:0.6480
Fold 3: ROC-AUC:0.7559
Fold 4: ROC-AUC:0.6806
Fold 5: ROC-AUC:0.5977

Mean ROC-AUC: 0.6633
Std: 0.0534

In [59]:
cv_models_Sex_F.append({'Model_Sex_F':'CatBoost_baseline_Sex_F',
                               'Mean ROC-AUC':Sex_F_base_cb_mean,
                               'Std': Sex_F_base_cb_std})
cv_models_Sex_F.append({'Model_Sex_F':'CatBoost_optune_Sex_F',
                               'Mean ROC-AUC':Sex_F_optune_cb_mean,
                               'Std':Sex_F_optune_cb_std})
cv_models_Sex_F_df = pd.DataFrame(cv_models_Sex_F)
round(cv_models_Sex_F_df.set_index('Model_Sex_F'), 3)

                                   Mean ROC-AUC    Std
Model_Sex_F
LogisticRegression_baseline_Sex_F         0.748  0.039
LogisticRegression_optune_Sex_F           0.744  0.030
LightGBM_baseline_Sex_F                   0.666  0.025
LightGBM_optune_Sex_F                     0.705  0.037
CatBoost_baseline_Sex_F                   0.668  0.055
CatBoost_optune_Sex_F                     0.663  0.053

# Стекинг

In [60]:
X_train_ADHD_ = X_train_ADHD_.reset_index(drop=True)
y_train_ADHD_ = y_train_ADHD_.reset_index(drop=True)

oof_lr_1 = pd.Series(np.zeros(len(X_train_ADHD_)))
oof_lgbm_1 = pd.Series(np.zeros(len(X_train_ADHD_)))
oof_cat_1 = pd.Series(np.zeros(len(X_train_ADHD_)))

test_lr_1 = np.zeros(len(X_val_ADHD))
test_lgbm_1 = np.zeros(len(X_val_ADHD))
test_cat_1 = np.zeros(len(X_val_ADHD))

In [61]:
X_train_Sex_F_ = X_train_Sex_F_.reset_index(drop=True)
y_train_Sex_F_ = y_train_Sex_F_.reset_index(drop=True)

oof_lr_2 = np.zeros(len(X_train_Sex_F_))
oof_lgbm_2 = np.zeros(len(X_train_Sex_F_))
oof_cat_2 = np.zeros(len(X_train_Sex_F_))

test_lr_2 = np.zeros(len(X_val_Sex_F))
test_lgbm_2 = np.zeros(len(X_val_Sex_F))
test_cat_2 = np.zeros(len(X_val_Sex_F))

In [62]:
# Pipeline / модели
lr_pipeline_1 = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(**best_params_lr_ADHD))
])

lgb_model_1 = LGBMClassifier(**best_params_ADHD_lgb, verbosity = -1)

cat_model_1 = CatBoostClassifier(
    **best_params_CB_ADHD,
    verbose=0
)

# KFold
kf = KFold(n_splits=5, shuffle=True, random_state=42)

for train_idx, val_idx in kf.split(X_train_ADHD_):

    X_tr = X_train_ADHD_.iloc[train_idx]
    X_val = X_train_ADHD_.iloc[val_idx]

    y_tr = y_train_ADHD_.iloc[train_idx]

    #Logistic Regression
    lr_pipeline_1.fit(X_tr, y_tr)
    oof_lr_1[val_idx] = lr_pipeline_1.predict_proba(X_val)[:, 1]

    #LightGBM
    lgb_model_1.fit(X_tr, y_tr)
    oof_lgbm_1[val_idx] = lgb_model_1.predict_proba(X_val)[:, 1]

    #CatBoost
    cat_model_1.fit(X_tr, y_tr)
    oof_cat_1[val_idx] = cat_model_1.predict_proba(X_val)[:, 1]

In [63]:
print("LR ROC-AUC:", roc_auc_score(y_train_ADHD_, oof_lr_1))
print("LGBM ROC-AUC:", roc_auc_score(y_train_ADHD_, oof_lgbm_1))
print("CatBoost ROC-AUC:", roc_auc_score(y_train_ADHD_, oof_cat_1))

LR ROC-AUC: 0.5650484849859043
LGBM ROC-AUC: 0.6596981308905667
CatBoost ROC-AUC: 0.6726224217551338

In [64]:
# OOF массивы для train 
X_meta_train_1 = np.column_stack([oof_lr_1, oof_lgbm_1, oof_cat_1])
y_meta_train_1 = y_train_ADHD_.values  # длина = len(X_meta_train)

y_meta_val_1 = y_train_ADHD_.values  # длина = len(X_meta_val)

In [65]:
len(X_train_ADHD)

941

In [66]:
meta_model_1 = LogisticRegression()
meta_model_1.fit(X_meta_train_1, y_train_ADHD_)

LogisticRegression()

In [67]:
lr_pipeline_1.fit(X_train_ADHD_, y_train_ADHD_)
lgb_model_1.fit(X_train_ADHD_, y_train_ADHD_)
cat_model_1.fit(X_train_ADHD_, y_train_ADHD_)

In [68]:
X_meta_val_1 = np.column_stack([
    lr_pipeline_1.predict_proba(X_val_ADHD)[:, 1],
    lgb_model_1.predict_proba(X_val_ADHD)[:, 1],
    cat_model_1.predict_proba(X_val_ADHD)[:, 1]
])

In [69]:
X_meta_val_1.shape[0] == len(y_val_ADHD)

True

In [70]:
oof_meta_ADHD = meta_model_1.predict_proba(X_meta_train_1)[:, 1]

In [71]:
print("Stacking ROC-AUC:", roc_auc_score(y_train_ADHD_, oof_meta_ADHD))

Stacking ROC-AUC: 0.6760688993190184

In [72]:
# Pipeline / модели
lr_pipeline_2 = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression())
])

lgb_model_2 = LGBMClassifier(**best_params_Sex_F_lgbm, verbosity = -1)

cat_model_2 = CatBoostClassifier()

# KFold
kf = KFold(n_splits=5, shuffle=True, random_state=42)

for train_idx, val_idx in kf.split(X_train_Sex_F_):

    X_tr = X_train_Sex_F_.iloc[train_idx]
    X_val = X_train_Sex_F_.iloc[val_idx]

    y_tr = y_train_Sex_F_.iloc[train_idx]

    #Logistic Regression
    lr_pipeline_2.fit(X_tr, y_tr)
    oof_lr_2[val_idx] = lr_pipeline_2.predict_proba(X_val)[:, 1]

    #LightGBM
    lgb_model_2.fit(X_tr, y_tr)
    oof_lgbm_2[val_idx] = lgb_model_2.predict_proba(X_val)[:, 1]

    #CatBoost
    cat_model_2.fit(X_tr, y_tr)
    oof_cat_2[val_idx] = cat_model_2.predict_proba(X_val)[:, 1]

Learning rate set to 0.008469
0:	learn: 0.6908085	total: 2.26s	remaining: 37m 36s
1:	learn: 0.6886030	total: 4.26s	remaining: 35m 25s
2:	learn: 0.6867400	total: 6.21s	remaining: 34m 24s
3:	learn: 0.6849954	total: 8.13s	remaining: 33m 44s
4:	learn: 0.6828964	total: 10.1s	remaining: 33m 35s
5:	learn: 0.6813312	total: 12.1s	remaining: 33m 28s
6:	learn: 0.6794630	total: 14.1s	remaining: 33m 23s
7:	learn: 0.6772889	total: 16.1s	remaining: 33m 13s
8:	learn: 0.6754546	total: 18s	remaining: 32m 57s
9:	learn: 0.6734036	total: 19.9s	remaining: 32m 51s
10:	learn: 0.6714266	total: 21.9s	remaining: 32m 45s
11:	learn: 0.6691441	total: 23.8s	remaining: 32m 38s
12:	learn: 0.6674061	total: 25.7s	remaining: 32m 32s
13:	learn: 0.6654216	total: 27.7s	remaining: 32m 31s
14:	learn: 0.6636903	total: 29.7s	remaining: 32m 32s
15:	learn: 0.6616958	total: 31.8s	remaining: 32m 35s
16:	learn: 0.6599812	total: 33.9s	remaining: 32m 41s
17:	learn: 0.6581721	total: 35.9s	remaining: 32m 40s
18:	learn: 0.6557816	total: 37.9s	remaining: 32m 37s
19:	learn: 0.6539519	total: 40.1s	remaining: 32m 42s
20:	learn: 0.6523433	total: 42.1s	remaining: 32m 44s
21:	learn: 0.6506427	total: 44.3s	remaining: 32m 47s
22:	learn: 0.6485429	total: 46.3s	remaining: 32m 48s
23:	learn: 0.6469353	total: 48.6s	remaining: 32m 54s
24:	learn: 0.6455112	total: 50.8s	remaining: 33m 2s
25:	learn: 0.6440427	total: 52.8s	remaining: 32m 59s
26:	learn: 0.6420198	total: 54.9s	remaining: 32m 58s
27:	learn: 0.6404236	total: 57.1s	remaining: 33m
28:	learn: 0.6390126	total: 59.2s	remaining: 33m 3s
29:	learn: 0.6374283	total: 1m 1s	remaining: 33m 1s
30:	learn: 0.6360479	total: 1m 3s	remaining: 32m 59s
31:	learn: 0.6342177	total: 1m 5s	remaining: 32m 58s
32:	learn: 0.6327134	total: 1m 7s	remaining: 32m 59s
33:	learn: 0.6312378	total: 1m 9s	remaining: 33m 2s
34:	learn: 0.6292529	total: 1m 11s	remaining: 33m 2s
35:	learn: 0.6277371	total: 1m 13s	remaining: 32m 58s
36:	learn: 0.6261676	total: 1m 15s	remaining: 32m 54s
37:	learn: 0.6243924	total: 1m 17s	remaining: 32m 49s
38:	learn: 0.6231577	total: 1m 19s	remaining: 32m 46s
39:	learn: 0.6213094	total: 1m 21s	remaining: 32m 42s
40:	learn: 0.6198955	total: 1m 23s	remaining: 32m 38s
41:	learn: 0.6187410	total: 1m 25s	remaining: 32m 33s
42:	learn: 0.6174812	total: 1m 27s	remaining: 32m 29s
43:	learn: 0.6158437	total: 1m 29s	remaining: 32m 24s
44:	learn: 0.6143067	total: 1m 31s	remaining: 32m 20s
45:	learn: 0.6125609	total: 1m 33s	remaining: 32m 22s
46:	learn: 0.6112145	total: 1m 35s	remaining: 32m 19s
47:	learn: 0.6099039	total: 1m 37s	remaining: 32m 16s
48:	learn: 0.6085174	total: 1m 39s	remaining: 32m 12s
49:	learn: 0.6075844	total: 1m 41s	remaining: 32m 9s
50:	learn: 0.6054606	total: 1m 43s	remaining: 32m 5s
51:	learn: 0.6040016	total: 1m 45s	remaining: 32m 1s
52:	learn: 0.6025526	total: 1m 47s	remaining: 31m 58s
53:	learn: 0.6017352	total: 1m 49s	remaining: 31m 55s
54:	learn: 0.6003851	total: 1m 51s	remaining: 31m 54s
55:	learn: 0.5990158	total: 1m 53s	remaining: 31m 52s
56:	learn: 0.5974133	total: 1m 55s	remaining: 31m 56s
57:	learn: 0.5961285	total: 1m 58s	remaining: 31m 56s
58:	learn: 0.5944022	total: 2m	remaining: 31m 56s
59:	learn: 0.5931907	total: 2m 2s	remaining: 31m 58s
60:	learn: 0.5921683	total: 2m 4s	remaining: 32m
61:	learn: 0.5907604	total: 2m 6s	remaining: 31m 58s
62:	learn: 0.5891172	total: 2m 8s	remaining: 31m 57s
63:	learn: 0.5877081	total: 2m 11s	remaining: 31m 59s
64:	learn: 0.5866875	total: 2m 13s	remaining: 31m 56s
65:	learn: 0.5853478	total: 2m 15s	remaining: 31m 55s
66:	learn: 0.5845991	total: 2m 17s	remaining: 31m 55s
67:	learn: 0.5835954	total: 2m 19s	remaining: 31m 54s
68:	learn: 0.5823704	total: 2m 21s	remaining: 31m 53s
69:	learn: 0.5807550	total: 2m 23s	remaining: 31m 52s
70:	learn: 0.5794036	total: 2m 25s	remaining: 31m 49s
71:	learn: 0.5775179	total: 2m 27s	remaining: 31m 45s
72:	learn: 0.5766155	total: 2m 29s	remaining: 31m 41s
73:	learn: 0.5752838	total: 2m 31s	remaining: 31m 38s
74:	learn: 0.5740811	total: 2m 33s	remaining: 31m 36s
75:	learn: 0.5727569	total: 2m 35s	remaining: 31m 32s
76:	learn: 0.5715367	total: 2m 37s	remaining: 31m 29s
77:	learn: 0.5700903	total: 2m 39s	remaining: 31m 26s
78:	learn: 0.5689177	total: 2m 41s	remaining: 31m 23s
79:	learn: 0.5674444	total: 2m 43s	remaining: 31m 20s
80:	learn: 0.5660521	total: 2m 45s	remaining: 31m 17s
81:	learn: 0.5646244	total: 2m 47s	remaining: 31m 14s
82:	learn: 0.5633673	total: 2m 49s	remaining: 31m 12s
83:	learn: 0.5620419	total: 2m 51s	remaining: 31m 8s
84:	learn: 0.5607095	total: 2m 53s	remaining: 31m 5s
85:	learn: 0.5593994	total: 2m 55s	remaining: 31m 2s
86:	learn: 0.5581134	total: 2m 57s	remaining: 30m 59s
87:	learn: 0.5568694	total: 2m 59s	remaining: 30m 57s
88:	learn: 0.5553444	total: 3m 1s	remaining: 30m 54s
89:	learn: 0.5542093	total: 3m 3s	remaining: 30m 52s
90:	learn: 0.5534127	total: 3m 5s	remaining: 30m 48s
91:	learn: 0.5523459	total: 3m 7s	remaining: 30m 46s
92:	learn: 0.5509623	total: 3m 8s	remaining: 30m 42s
93:	learn: 0.5499466	total: 3m 10s	remaining: 30m 40s
94:	learn: 0.5488666	total: 3m 12s	remaining: 30m 37s
95:	learn: 0.5477960	total: 3m 14s	remaining: 30m 35s
96:	learn: 0.5463576	total: 3m 16s	remaining: 30m 32s
97:	learn: 0.5452568	total: 3m 18s	remaining: 30m 29s
98:	learn: 0.5443277	total: 3m 20s	remaining: 30m 27s
99:	learn: 0.5433457	total: 3m 22s	remaining: 30m 25s
100:	learn: 0.5420949	total: 3m 24s	remaining: 30m 22s
101:	learn: 0.5409477	total: 3m 26s	remaining: 30m 19s
102:	learn: 0.5396671	total: 3m 28s	remaining: 30m 17s
103:	learn: 0.5388738	total: 3m 30s	remaining: 30m 14s
104:	learn: 0.5378635	total: 3m 32s	remaining: 30m 12s
105:	learn: 0.5366514	total: 3m 34s	remaining: 30m 9s
106:	learn: 0.5354248	total: 3m 36s	remaining: 30m 7s
107:	learn: 0.5345924	total: 3m 38s	remaining: 30m 4s
108:	learn: 0.5333995	total: 3m 40s	remaining: 30m 2s
109:	learn: 0.5325278	total: 3m 42s	remaining: 30m
110:	learn: 0.5315392	total: 3m 44s	remaining: 29m 57s
111:	learn: 0.5301871	total: 3m 46s	remaining: 29m 54s
112:	learn: 0.5292392	total: 3m 48s	remaining: 29m 52s
113:	learn: 0.5280617	total: 3m 50s	remaining: 29m 50s
114:	learn: 0.5266813	total: 3m 52s	remaining: 29m 47s
115:	learn: 0.5260506	total: 3m 54s	remaining: 29m 45s
116:	learn: 0.5247661	total: 3m 56s	remaining: 29m 43s
117:	learn: 0.5236274	total: 3m 58s	remaining: 29m 41s
118:	learn: 0.5227560	total: 4m	remaining: 29m 39s
119:	learn: 0.5215470	total: 4m 2s	remaining: 29m 36s
120:	learn: 0.5207138	total: 4m 4s	remaining: 29m 34s
121:	learn: 0.5195101	total: 4m 6s	remaining: 29m 31s
122:	learn: 0.5184651	total: 4m 8s	remaining: 29m 29s
123:	learn: 0.5172322	total: 4m 10s	remaining: 29m 28s
124:	learn: 0.5160448	total: 4m 12s	remaining: 29m 25s
125:	learn: 0.5150102	total: 4m 14s	remaining: 29m 23s
126:	learn: 0.5134395	total: 4m 16s	remaining: 29m 21s
127:	learn: 0.5121363	total: 4m 18s	remaining: 29m 19s
128:	learn: 0.5109055	total: 4m 20s	remaining: 29m 17s
129:	learn: 0.5098462	total: 4m 22s	remaining: 29m 15s
130:	learn: 0.5086685	total: 4m 24s	remaining: 29m 13s
131:	learn: 0.5077297	total: 4m 26s	remaining: 29m 11s
132:	learn: 0.5067394	total: 4m 28s	remaining: 29m 9s
133:	learn: 0.5060703	total: 4m 30s	remaining: 29m 6s
134:	learn: 0.5049667	total: 4m 32s	remaining: 29m 4s
135:	learn: 0.5035125	total: 4m 34s	remaining: 29m 2s
136:	learn: 0.5027214	total: 4m 36s	remaining: 28m 59s
137:	learn: 0.5018741	total: 4m 38s	remaining: 28m 57s
138:	learn: 0.5009650	total: 4m 40s	remaining: 28m 55s
139:	learn: 0.5002451	total: 4m 42s	remaining: 28m 52s
140:	learn: 0.4990130	total: 4m 44s	remaining: 28m 50s
141:	learn: 0.4979315	total: 4m 46s	remaining: 28m 48s
142:	learn: 0.4971214	total: 4m 48s	remaining: 28m 46s
143:	learn: 0.4962654	total: 4m 49s	remaining: 28m 43s
144:	learn: 0.4951308	total: 4m 52s	remaining: 28m 41s
145:	learn: 0.4938517	total: 4m 54s	remaining: 28m 39s
146:	learn: 0.4923970	total: 4m 56s	remaining: 28m 37s
147:	learn: 0.4916050	total: 4m 58s	remaining: 28m 35s
148:	learn: 0.4906084	total: 4m 59s	remaining: 28m 33s
149:	learn: 0.4895863	total: 5m 2s	remaining: 28m 31s
150:	learn: 0.4884135	total: 5m 4s	remaining: 28m 29s
151:	learn: 0.4875989	total: 5m 6s	remaining: 28m 27s
152:	learn: 0.4867980	total: 5m 8s	remaining: 28m 25s
153:	learn: 0.4860674	total: 5m 9s	remaining: 28m 22s
154:	learn: 0.4851854	total: 5m 11s	remaining: 28m 20s
155:	learn: 0.4843342	total: 5m 13s	remaining: 28m 18s
156:	learn: 0.4833719	total: 5m 15s	remaining: 28m 16s
157:	learn: 0.4825456	total: 5m 17s	remaining: 28m 13s
158:	learn: 0.4811454	total: 5m 19s	remaining: 28m 11s
159:	learn: 0.4801910	total: 5m 21s	remaining: 28m 9s
160:	learn: 0.4792284	total: 5m 23s	remaining: 28m 7s
161:	learn: 0.4782245	total: 5m 25s	remaining: 28m 5s
162:	learn: 0.4772993	total: 5m 27s	remaining: 28m 3s
163:	learn: 0.4763997	total: 5m 29s	remaining: 28m
164:	learn: 0.4753487	total: 5m 31s	remaining: 27m 58s
165:	learn: 0.4742642	total: 5m 33s	remaining: 27m 56s
166:	learn: 0.4732442	total: 5m 35s	remaining: 27m 54s
167:	learn: 0.4725238	total: 5m 37s	remaining: 27m 52s
168:	learn: 0.4713194	total: 5m 39s	remaining: 27m 50s
169:	learn: 0.4701131	total: 5m 41s	remaining: 27m 49s
170:	learn: 0.4691709	total: 5m 44s	remaining: 27m 48s
171:	learn: 0.4682320	total: 5m 46s	remaining: 27m 46s
172:	learn: 0.4670809	total: 5m 48s	remaining: 27m 44s
173:	learn: 0.4658045	total: 5m 50s	remaining: 27m 42s
174:	learn: 0.4650326	total: 5m 52s	remaining: 27m 41s
175:	learn: 0.4644483	total: 5m 54s	remaining: 27m 39s
176:	learn: 0.4636238	total: 5m 56s	remaining: 27m 38s
177:	learn: 0.4627082	total: 5m 58s	remaining: 27m 36s
178:	learn: 0.4619006	total: 6m	remaining: 27m 34s
179:	learn: 0.4610054	total: 6m 2s	remaining: 27m 33s
180:	learn: 0.4603070	total: 6m 4s	remaining: 27m 31s
181:	learn: 0.4595158	total: 6m 6s	remaining: 27m 28s
182:	learn: 0.4586837	total: 6m 8s	remaining: 27m 26s
183:	learn: 0.4575880	total: 6m 10s	remaining: 27m 24s
184:	learn: 0.4564908	total: 6m 12s	remaining: 27m 22s
185:	learn: 0.4558065	total: 6m 14s	remaining: 27m 20s
186:	learn: 0.4552505	total: 6m 16s	remaining: 27m 18s
187:	learn: 0.4542317	total: 6m 18s	remaining: 27m 15s
188:	learn: 0.4533654	total: 6m 20s	remaining: 27m 13s
189:	learn: 0.4526851	total: 6m 22s	remaining: 27m 11s
190:	learn: 0.4514001	total: 6m 24s	remaining: 27m 8s
191:	learn: 0.4505029	total: 6m 26s	remaining: 27m 6s
192:	learn: 0.4495707	total: 6m 28s	remaining: 27m 4s
193:	learn: 0.4487087	total: 6m 30s	remaining: 27m 1s
194:	learn: 0.4478971	total: 6m 32s	remaining: 26m 59s
195:	learn: 0.4471406	total: 6m 34s	remaining: 26m 57s
196:	learn: 0.4460869	total: 6m 36s	remaining: 26m 54s
197:	learn: 0.4453615	total: 6m 38s	remaining: 26m 52s
198:	learn: 0.4446990	total: 6m 40s	remaining: 26m 50s
199:	learn: 0.4437932	total: 6m 41s	remaining: 26m 47s
200:	learn: 0.4427265	total: 6m 43s	remaining: 26m 45s
201:	learn: 0.4415716	total: 6m 45s	remaining: 26m 43s
202:	learn: 0.4406988	total: 6m 47s	remaining: 26m 41s
203:	learn: 0.4398776	total: 6m 49s	remaining: 26m 38s
204:	learn: 0.4392167	total: 6m 51s	remaining: 26m 36s
205:	learn: 0.4381223	total: 6m 53s	remaining: 26m 34s
206:	learn: 0.4370330	total: 6m 55s	remaining: 26m 32s
207:	learn: 0.4362855	total: 6m 57s	remaining: 26m 30s
208:	learn: 0.4354818	total: 6m 59s	remaining: 26m 28s
209:	learn: 0.4348319	total: 7m 1s	remaining: 26m 27s
210:	learn: 0.4340640	total: 7m 4s	remaining: 26m 25s
211:	learn: 0.4333388	total: 7m 6s	remaining: 26m 23s
212:	learn: 0.4326240	total: 7m 8s	remaining: 26m 21s
213:	learn: 0.4317870	total: 7m 10s	remaining: 26m 20s
214:	learn: 0.4308216	total: 7m 12s	remaining: 26m 19s
215:	learn: 0.4299602	total: 7m 14s	remaining: 26m 16s
216:	learn: 0.4291002	total: 7m 16s	remaining: 26m 14s
217:	learn: 0.4281712	total: 7m 18s	remaining: 26m 12s
218:	learn: 0.4273435	total: 7m 20s	remaining: 26m 11s
219:	learn: 0.4264278	total: 7m 22s	remaining: 26m 9s
220:	learn: 0.4255550	total: 7m 24s	remaining: 26m 7s
221:	learn: 0.4246430	total: 7m 26s	remaining: 26m 5s
222:	learn: 0.4240422	total: 7m 28s	remaining: 26m 3s
223:	learn: 0.4230751	total: 7m 30s	remaining: 26m 1s
224:	learn: 0.4222488	total: 7m 32s	remaining: 25m 59s
225:	learn: 0.4215662	total: 7m 34s	remaining: 25m 57s
226:	learn: 0.4209525	total: 7m 36s	remaining: 25m 54s
227:	learn: 0.4203566	total: 7m 38s	remaining: 25m 52s
228:	learn: 0.4194318	total: 7m 40s	remaining: 25m 50s
229:	learn: 0.4185151	total: 7m 42s	remaining: 25m 48s
230:	learn: 0.4177240	total: 7m 44s	remaining: 25m 46s
231:	learn: 0.4168173	total: 7m 46s	remaining: 25m 44s
232:	learn: 0.4157338	total: 7m 48s	remaining: 25m 42s
233:	learn: 0.4147399	total: 7m 50s	remaining: 25m 40s
234:	learn: 0.4139788	total: 7m 52s	remaining: 25m 38s
235:	learn: 0.4131906	total: 7m 54s	remaining: 25m 36s
236:	learn: 0.4121043	total: 7m 56s	remaining: 25m 34s
237:	learn: 0.4115001	total: 7m 58s	remaining: 25m 32s
238:	learn: 0.4109880	total: 8m	remaining: 25m 30s
239:	learn: 0.4103006	total: 8m 2s	remaining: 25m 27s
240:	learn: 0.4095560	total: 8m 4s	remaining: 25m 25s
241:	learn: 0.4085081	total: 8m 6s	remaining: 25m 23s
242:	learn: 0.4075635	total: 8m 8s	remaining: 25m 21s
243:	learn: 0.4065511	total: 8m 10s	remaining: 25m 19s
244:	learn: 0.4058063	total: 8m 12s	remaining: 25m 17s
245:	learn: 0.4050220	total: 8m 14s	remaining: 25m 15s
246:	learn: 0.4039465	total: 8m 16s	remaining: 25m 12s
247:	learn: 0.4034477	total: 8m 18s	remaining: 25m 10s
248:	learn: 0.4022933	total: 8m 20s	remaining: 25m 8s
249:	learn: 0.4016470	total: 8m 22s	remaining: 25m 6s
250:	learn: 0.4005931	total: 8m 24s	remaining: 25m 4s
251:	learn: 0.3997935	total: 8m 26s	remaining: 25m 2s
252:	learn: 0.3990717	total: 8m 28s	remaining: 25m
253:	learn: 0.3984511	total: 8m 30s	remaining: 24m 58s
254:	learn: 0.3977632	total: 8m 32s	remaining: 24m 55s
255:	learn: 0.3968798	total: 8m 34s	remaining: 24m 54s
256:	learn: 0.3962825	total: 8m 36s	remaining: 24m 54s
257:	learn: 0.3956428	total: 8m 38s	remaining: 24m 52s
258:	learn: 0.3948395	total: 8m 40s	remaining: 24m 50s
259:	learn: 0.3942030	total: 8m 42s	remaining: 24m 48s
260:	learn: 0.3934905	total: 8m 44s	remaining: 24m 45s
261:	learn: 0.3929453	total: 8m 47s	remaining: 24m 44s
262:	learn: 0.3921574	total: 8m 48s	remaining: 24m 42s
263:	learn: 0.3914974	total: 8m 50s	remaining: 24m 40s
264:	learn: 0.3907215	total: 8m 52s	remaining: 24m 38s
265:	learn: 0.3900751	total: 8m 54s	remaining: 24m 36s
266:	learn: 0.3897533	total: 8m 56s	remaining: 24m 34s
267:	learn: 0.3891331	total: 8m 59s	remaining: 24m 32s
268:	learn: 0.3884400	total: 9m 1s	remaining: 24m 30s
269:	learn: 0.3877965	total: 9m 3s	remaining: 24m 28s
270:	learn: 0.3867482	total: 9m 5s	remaining: 24m 26s
271:	learn: 0.3861754	total: 9m 7s	remaining: 24m 24s
272:	learn: 0.3854119	total: 9m 8s	remaining: 24m 21s
273:	learn: 0.3847235	total: 9m 10s	remaining: 24m 19s
274:	learn: 0.3839123	total: 9m 12s	remaining: 24m 17s
275:	learn: 0.3831786	total: 9m 14s	remaining: 24m 15s
276:	learn: 0.3825363	total: 9m 16s	remaining: 24m 13s
277:	learn: 0.3819994	total: 9m 18s	remaining: 24m 11s
278:	learn: 0.3812573	total: 9m 20s	remaining: 24m 9s
279:	learn: 0.3806992	total: 9m 22s	remaining: 24m 7s
280:	learn: 0.3799311	total: 9m 24s	remaining: 24m 5s
281:	learn: 0.3791221	total: 9m 26s	remaining: 24m 2s
282:	learn: 0.3784516	total: 9m 28s	remaining: 24m
283:	learn: 0.3775849	total: 9m 30s	remaining: 23m 58s
284:	learn: 0.3769233	total: 9m 32s	remaining: 23m 56s
285:	learn: 0.3763423	total: 9m 34s	remaining: 23m 54s
286:	learn: 0.3757016	total: 9m 36s	remaining: 23m 52s
287:	learn: 0.3752081	total: 9m 38s	remaining: 23m 50s
288:	learn: 0.3746556	total: 9m 40s	remaining: 23m 47s
289:	learn: 0.3738786	total: 9m 42s	remaining: 23m 45s
290:	learn: 0.3732161	total: 9m 44s	remaining: 23m 43s
291:	learn: 0.3723161	total: 9m 46s	remaining: 23m 41s
292:	learn: 0.3714842	total: 9m 48s	remaining: 23m 39s
293:	learn: 0.3708715	total: 9m 50s	remaining: 23m 37s
294:	learn: 0.3701778	total: 9m 52s	remaining: 23m 35s
295:	learn: 0.3696830	total: 9m 54s	remaining: 23m 33s
296:	learn: 0.3692812	total: 9m 56s	remaining: 23m 31s
297:	learn: 0.3685322	total: 9m 58s	remaining: 23m 29s
298:	learn: 0.3677846	total: 10m	remaining: 23m 26s
299:	learn: 0.3672158	total: 10m 2s	remaining: 23m 24s
300:	learn: 0.3664714	total: 10m 4s	remaining: 23m 22s
301:	learn: 0.3657127	total: 10m 5s	remaining: 23m 20s
302:	learn: 0.3650208	total: 10m 7s	remaining: 23m 18s
303:	learn: 0.3643195	total: 10m 9s	remaining: 23m 16s
304:	learn: 0.3637561	total: 10m 11s	remaining: 23m 14s
305:	learn: 0.3631235	total: 10m 13s	remaining: 23m 12s
306:	learn: 0.3625609	total: 10m 15s	remaining: 23m 9s
307:	learn: 0.3619120	total: 10m 17s	remaining: 23m 7s
308:	learn: 0.3612781	total: 10m 19s	remaining: 23m 5s
309:	learn: 0.3602076	total: 10m 21s	remaining: 23m 3s
310:	learn: 0.3592089	total: 10m 23s	remaining: 23m 1s
311:	learn: 0.3586679	total: 10m 25s	remaining: 22m 59s
312:	learn: 0.3582059	total: 10m 27s	remaining: 22m 57s
313:	learn: 0.3578944	total: 10m 29s	remaining: 22m 55s
314:	learn: 0.3573854	total: 10m 31s	remaining: 22m 54s
315:	learn: 0.3567234	total: 10m 33s	remaining: 22m 52s
316:	learn: 0.3562243	total: 10m 36s	remaining: 22m 50s
317:	learn: 0.3555474	total: 10m 38s	remaining: 22m 48s
318:	learn: 0.3547566	total: 10m 40s	remaining: 22m 46s
319:	learn: 0.3539818	total: 10m 42s	remaining: 22m 44s
320:	learn: 0.3533355	total: 10m 44s	remaining: 22m 42s
321:	learn: 0.3523476	total: 10m 46s	remaining: 22m 40s
322:	learn: 0.3515866	total: 10m 48s	remaining: 22m 38s
323:	learn: 0.3510478	total: 10m 50s	remaining: 22m 36s
324:	learn: 0.3505235	total: 10m 52s	remaining: 22m 34s
325:	learn: 0.3497116	total: 10m 54s	remaining: 22m 32s
326:	learn: 0.3491551	total: 10m 56s	remaining: 22m 30s
327:	learn: 0.3486468	total: 10m 58s	remaining: 22m 28s
328:	learn: 0.3480242	total: 11m	remaining: 22m 26s
329:	learn: 0.3473594	total: 11m 2s	remaining: 22m 24s
330:	learn: 0.3466073	total: 11m 4s	remaining: 22m 22s
331:	learn: 0.3459026	total: 11m 6s	remaining: 22m 20s
332:	learn: 0.3450904	total: 11m 8s	remaining: 22m 18s
333:	learn: 0.3446440	total: 11m 10s	remaining: 22m 15s
334:	learn: 0.3440246	total: 11m 11s	remaining: 22m 13s
335:	learn: 0.3435192	total: 11m 14s	remaining: 22m 12s
336:	learn: 0.3430334	total: 11m 16s	remaining: 22m 9s
337:	learn: 0.3426025	total: 11m 17s	remaining: 22m 7s
338:	learn: 0.3420960	total: 11m 19s	remaining: 22m 5s
339:	learn: 0.3414733	total: 11m 21s	remaining: 22m 3s
340:	learn: 0.3409624	total: 11m 23s	remaining: 22m 1s
341:	learn: 0.3402677	total: 11m 25s	remaining: 21m 59s
342:	learn: 0.3394703	total: 11m 27s	remaining: 21m 57s
343:	learn: 0.3390014	total: 11m 30s	remaining: 21m 56s
344:	learn: 0.3382748	total: 11m 32s	remaining: 21m 54s
345:	learn: 0.3375080	total: 11m 34s	remaining: 21m 52s
346:	learn: 0.3367391	total: 11m 36s	remaining: 21m 50s
347:	learn: 0.3361513	total: 11m 38s	remaining: 21m 48s
348:	learn: 0.3354341	total: 11m 40s	remaining: 21m 45s
349:	learn: 0.3347441	total: 11m 42s	remaining: 21m 43s
350:	learn: 0.3340746	total: 11m 44s	remaining: 21m 41s
351:	learn: 0.3333816	total: 11m 46s	remaining: 21m 39s
352:	learn: 0.3326284	total: 11m 48s	remaining: 21m 37s
353:	learn: 0.3320335	total: 11m 49s	remaining: 21m 35s
354:	learn: 0.3315045	total: 11m 51s	remaining: 21m 33s
355:	learn: 0.3308090	total: 11m 54s	remaining: 21m 31s
356:	learn: 0.3300513	total: 11m 55s	remaining: 21m 29s
357:	learn: 0.3293064	total: 11m 57s	remaining: 21m 27s
358:	learn: 0.3287408	total: 11m 59s	remaining: 21m 25s
359:	learn: 0.3281782	total: 12m 1s	remaining: 21m 23s
360:	learn: 0.3273750	total: 12m 3s	remaining: 21m 21s
361:	learn: 0.3265312	total: 12m 5s	remaining: 21m 19s
362:	learn: 0.3259379	total: 12m 7s	remaining: 21m 17s
363:	learn: 0.3253151	total: 12m 9s	remaining: 21m 15s
364:	learn: 0.3246643	total: 12m 11s	remaining: 21m 13s
365:	learn: 0.3240159	total: 12m 13s	remaining: 21m 11s
366:	learn: 0.3234966	total: 12m 15s	remaining: 21m 9s

In [73]:
print("LR ROC-AUC:", roc_auc_score(y_train_Sex_F_, oof_lr_2))
print("LGBM ROC-AUC:", roc_auc_score(y_train_Sex_F_, oof_lgbm_2))
print("CatBoost ROC-AUC:", roc_auc_score(y_train_Sex_F_, oof_cat_2))

LR ROC-AUC: 0.7741967593086335
LGBM ROC-AUC: 0.7045339817560025
CatBoost ROC-AUC: 0.6756322476519564

In [74]:
# --- 1. OOF массивы для train (которые уже есть) ---
X_meta_train_2 = np.column_stack([oof_lr_2, oof_lgbm_2, oof_cat_2])
y_meta_train_2 = y_train_Sex_F_.values  # длина = len(X_meta_train)

y_meta_val_2 = y_train_Sex_F_.values  # длина = len(X_meta_val)

In [75]:
meta_model_2 = LogisticRegression()
meta_model_2.fit(X_meta_train_2, y_train_Sex_F_)

LogisticRegression()

In [76]:
lr_pipeline_2.fit(X_train_Sex_F_, y_train_Sex_F_)
lgb_model_2.fit(X_train_Sex_F_, y_train_Sex_F_)
cat_model_2.fit(X_train_Sex_F_, y_train_Sex_F_)

Learning rate set to 0.009316
0:	learn: 0.6909742	total: 2.33s	remaining: 38m 44s
1:	learn: 0.6885555	total: 4.33s	remaining: 36m
2:	learn: 0.6867613	total: 6.26s	remaining: 34m 41s
3:	learn: 0.6848765	total: 8.23s	remaining: 34m 10s
4:	learn: 0.6831189	total: 10.2s	remaining: 33m 50s
5:	learn: 0.6812263	total: 12.2s	remaining: 33m 35s
6:	learn: 0.6791170	total: 14.1s	remaining: 33m 25s
7:	learn: 0.6776160	total: 16s	remaining: 33m 9s
8:	learn: 0.6755188	total: 18s	remaining: 32m 59s
9:	learn: 0.6729870	total: 20s	remaining: 32m 56s
10:	learn: 0.6709572	total: 21.9s	remaining: 32m 53s
11:	learn: 0.6688320	total: 23.9s	remaining: 32m 45s
12:	learn: 0.6665931	total: 25.8s	remaining: 32m 39s
13:	learn: 0.6648568	total: 27.8s	remaining: 32m 38s
14:	learn: 0.6629037	total: 29.8s	remaining: 32m 39s
15:	learn: 0.6609991	total: 32s	remaining: 32m 46s
16:	learn: 0.6591638	total: 34.1s	remaining: 32m 52s
17:	learn: 0.6572115	total: 36.2s	remaining: 32m 54s
18:	learn: 0.6553705	total: 38.2s	remaining: 32m 49s
19:	learn: 0.6538192	total: 40.3s	remaining: 32m 53s
20:	learn: 0.6520844	total: 42.5s	remaining: 32m 59s
21:	learn: 0.6501831	total: 44.6s	remaining: 33m 4s
22:	learn: 0.6484326	total: 46.7s	remaining: 33m 4s
23:	learn: 0.6467814	total: 48.8s	remaining: 33m 4s
24:	learn: 0.6454456	total: 51s	remaining: 33m 9s
25:	learn: 0.6438532	total: 53.2s	remaining: 33m 11s
26:	learn: 0.6421672	total: 55.2s	remaining: 33m 8s
27:	learn: 0.6403639	total: 57.5s	remaining: 33m 14s
28:	learn: 0.6388607	total: 59.7s	remaining: 33m 19s
29:	learn: 0.6372656	total: 1m 1s	remaining: 33m 20s
30:	learn: 0.6358074	total: 1m 3s	remaining: 33m 18s
31:	learn: 0.6342132	total: 1m 5s	remaining: 33m 13s
32:	learn: 0.6330692	total: 1m 8s	remaining: 33m 14s
33:	learn: 0.6310574	total: 1m 10s	remaining: 33m 17s
34:	learn: 0.6294628	total: 1m 12s	remaining: 33m 15s
35:	learn: 0.6280502	total: 1m 14s	remaining: 33m 16s
36:	learn: 0.6260247	total: 1m 16s	remaining: 33m 19s
37:	learn: 0.6245905	total: 1m 18s	remaining: 33m 15s
38:	learn: 0.6226288	total: 1m 20s	remaining: 33m 12s
39:	learn: 0.6213788	total: 1m 22s	remaining: 33m 9s
40:	learn: 0.6200990	total: 1m 24s	remaining: 33m 4s
41:	learn: 0.6187583	total: 1m 26s	remaining: 32m 59s
42:	learn: 0.6173534	total: 1m 28s	remaining: 32m 55s
43:	learn: 0.6158840	total: 1m 30s	remaining: 32m 52s
44:	learn: 0.6147060	total: 1m 32s	remaining: 32m 48s
45:	learn: 0.6127394	total: 1m 34s	remaining: 32m 44s
46:	learn: 0.6113982	total: 1m 36s	remaining: 32m 41s
47:	learn: 0.6097905	total: 1m 38s	remaining: 32m 37s
48:	learn: 0.6086126	total: 1m 40s	remaining: 32m 34s
49:	learn: 0.6072943	total: 1m 42s	remaining: 32m 29s
50:	learn: 0.6060808	total: 1m 44s	remaining: 32m 25s
51:	learn: 0.6046592	total: 1m 46s	remaining: 32m 22s
52:	learn: 0.6032628	total: 1m 48s	remaining: 32m 19s
53:	learn: 0.6014913	total: 1m 50s	remaining: 32m 15s
54:	learn: 0.5994079	total: 1m 52s	remaining: 32m 12s
55:	learn: 0.5981142	total: 1m 54s	remaining: 32m 8s
56:	learn: 0.5965132	total: 1m 56s	remaining: 32m 6s
57:	learn: 0.5948260	total: 1m 58s	remaining: 32m 3s
58:	learn: 0.5935136	total: 2m	remaining: 31m 59s
59:	learn: 0.5920973	total: 2m 2s	remaining: 31m 56s
60:	learn: 0.5901564	total: 2m 4s	remaining: 31m 53s
61:	learn: 0.5890611	total: 2m 6s	remaining: 31m 51s
62:	learn: 0.5878698	total: 2m 8s	remaining: 31m 51s
63:	learn: 0.5864252	total: 2m 10s	remaining: 31m 51s
64:	learn: 0.5853429	total: 2m 12s	remaining: 31m 47s
65:	learn: 0.5840708	total: 2m 14s	remaining: 31m 45s
66:	learn: 0.5824620	total: 2m 16s	remaining: 31m 43s
67:	learn: 0.5811053	total: 2m 18s	remaining: 31m 42s
68:	learn: 0.5796204	total: 2m 21s	remaining: 31m 42s
69:	learn: 0.5783232	total: 2m 23s	remaining: 31m 42s
70:	learn: 0.5767425	total: 2m 25s	remaining: 31m 43s
71:	learn: 0.5756391	total: 2m 27s	remaining: 31m 41s
72:	learn: 0.5748951	total: 2m 29s	remaining: 31m 40s
73:	learn: 0.5737170	total: 2m 31s	remaining: 31m 40s
74:	learn: 0.5723978	total: 2m 34s	remaining: 31m 42s
75:	learn: 0.5712373	total: 2m 36s	remaining: 31m 42s
76:	learn: 0.5703114	total: 2m 38s	remaining: 31m 40s
77:	learn: 0.5692021	total: 2m 40s	remaining: 31m 40s
78:	learn: 0.5680652	total: 2m 42s	remaining: 31m 39s
79:	learn: 0.5669592	total: 2m 45s	remaining: 31m 39s
80:	learn: 0.5659447	total: 2m 47s	remaining: 31m 37s
81:	learn: 0.5649604	total: 2m 49s	remaining: 31m 34s
82:	learn: 0.5631324	total: 2m 51s	remaining: 31m 31s
83:	learn: 0.5615069	total: 2m 53s	remaining: 31m 28s
84:	learn: 0.5602559	total: 2m 55s	remaining: 31m 25s
85:	learn: 0.5593573	total: 2m 57s	remaining: 31m 23s
86:	learn: 0.5582578	total: 2m 59s	remaining: 31m 20s
87:	learn: 0.5571676	total: 3m 1s	remaining: 31m 17s
88:	learn: 0.5559148	total: 3m 3s	remaining: 31m 15s
89:	learn: 0.5547865	total: 3m 5s	remaining: 31m 12s
90:	learn: 0.5539608	total: 3m 7s	remaining: 31m 10s
91:	learn: 0.5529117	total: 3m 9s	remaining: 31m 7s
92:	learn: 0.5520493	total: 3m 11s	remaining: 31m 4s
93:	learn: 0.5507959	total: 3m 13s	remaining: 31m 2s
94:	learn: 0.5493658	total: 3m 15s	remaining: 30m 59s
95:	learn: 0.5480892	total: 3m 17s	remaining: 30m 56s
96:	learn: 0.5466310	total: 3m 19s	remaining: 30m 53s
97:	learn: 0.5457267	total: 3m 21s	remaining: 30m 50s
98:	learn: 0.5445482	total: 3m 23s	remaining: 30m 47s
99:	learn: 0.5436049	total: 3m 25s	remaining: 30m 45s
100:	learn: 0.5425334	total: 3m 26s	remaining: 30m 42s
101:	learn: 0.5419065	total: 3m 28s	remaining: 30m 39s
102:	learn: 0.5406538	total: 3m 30s	remaining: 30m 36s
103:	learn: 0.5390109	total: 3m 32s	remaining: 30m 34s
104:	learn: 0.5378640	total: 3m 34s	remaining: 30m 31s
105:	learn: 0.5366300	total: 3m 36s	remaining: 30m 28s
106:	learn: 0.5356823	total: 3m 38s	remaining: 30m 25s
107:	learn: 0.5341932	total: 3m 40s	remaining: 30m 23s
108:	learn: 0.5329340	total: 3m 42s	remaining: 30m 20s
109:	learn: 0.5319933	total: 3m 44s	remaining: 30m 17s
110:	learn: 0.5309122	total: 3m 46s	remaining: 30m 15s
111:	learn: 0.5296928	total: 3m 48s	remaining: 30m 12s
112:	learn: 0.5287563	total: 3m 50s	remaining: 30m 10s
113:	learn: 0.5276415	total: 3m 52s	remaining: 30m 8s
114:	learn: 0.5265838	total: 3m 54s	remaining: 30m 5s
115:	learn: 0.5259307	total: 3m 56s	remaining: 30m 2s
116:	learn: 0.5247689	total: 3m 58s	remaining: 30m 1s
117:	learn: 0.5238178	total: 4m	remaining: 29m 59s
118:	learn: 0.5225690	total: 4m 2s	remaining: 29m 58s
119:	learn: 0.5214574	total: 4m 4s	remaining: 29m 56s
120:	learn: 0.5204456	total: 4m 7s	remaining: 29m 55s
121:	learn: 0.5196168	total: 4m 9s	remaining: 29m 53s
122:	learn: 0.5179562	total: 4m 11s	remaining: 29m 50s
123:	learn: 0.5170971	total: 4m 13s	remaining: 29m 48s
124:	learn: 0.5161073	total: 4m 15s	remaining: 29m 46s
125:	learn: 0.5149135	total: 4m 17s	remaining: 29m 44s
126:	learn: 0.5140119	total: 4m 19s	remaining: 29m 42s
127:	learn: 0.5129283	total: 4m 21s	remaining: 29m 40s
128:	learn: 0.5120840	total: 4m 23s	remaining: 29m 38s
129:	learn: 0.5110071	total: 4m 25s	remaining: 29m 36s
130:	learn: 0.5098103	total: 4m 27s	remaining: 29m 34s
131:	learn: 0.5087533	total: 4m 29s	remaining: 29m 32s
132:	learn: 0.5077503	total: 4m 31s	remaining: 29m 30s
133:	learn: 0.5067916	total: 4m 33s	remaining: 29m 28s
134:	learn: 0.5057592	total: 4m 35s	remaining: 29m 26s
135:	learn: 0.5044621	total: 4m 37s	remaining: 29m 23s
136:	learn: 0.5033738	total: 4m 39s	remaining: 29m 21s
137:	learn: 0.5025755	total: 4m 41s	remaining: 29m 19s
138:	learn: 0.5016176	total: 4m 43s	remaining: 29m 17s
139:	learn: 0.5008024	total: 4m 45s	remaining: 29m 15s
140:	learn: 0.4998611	total: 4m 47s	remaining: 29m 13s
141:	learn: 0.4988057	total: 4m 49s	remaining: 29m 10s
142:	learn: 0.4975583	total: 4m 51s	remaining: 29m 8s
143:	learn: 0.4963771	total: 4m 53s	remaining: 29m 6s
144:	learn: 0.4955512	total: 4m 55s	remaining: 29m 4s
145:	learn: 0.4944301	total: 4m 57s	remaining: 29m 1s
146:	learn: 0.4935425	total: 4m 59s	remaining: 28m 59s
147:	learn: 0.4924911	total: 5m 1s	remaining: 28m 57s
148:	learn: 0.4914109	total: 5m 3s	remaining: 28m 55s
149:	learn: 0.4903962	total: 5m 5s	remaining: 28m 53s
150:	learn: 0.4893280	total: 5m 7s	remaining: 28m 51s
151:	learn: 0.4882590	total: 5m 10s	remaining: 28m 49s
152:	learn: 0.4870798	total: 5m 12s	remaining: 28m 47s
153:	learn: 0.4859092	total: 5m 14s	remaining: 28m 45s
154:	learn: 0.4852496	total: 5m 16s	remaining: 28m 43s
155:	learn: 0.4844899	total: 5m 18s	remaining: 28m 40s
156:	learn: 0.4834039	total: 5m 20s	remaining: 28m 38s
157:	learn: 0.4821399	total: 5m 22s	remaining: 28m 36s
158:	learn: 0.4811129	total: 5m 24s	remaining: 28m 34s
159:	learn: 0.4803579	total: 5m 26s	remaining: 28m 32s
160:	learn: 0.4794119	total: 5m 28s	remaining: 28m 30s
161:	learn: 0.4786518	total: 5m 30s	remaining: 28m 29s
162:	learn: 0.4778097	total: 5m 32s	remaining: 28m 27s
163:	learn: 0.4767192	total: 5m 34s	remaining: 28m 25s
164:	learn: 0.4756658	total: 5m 36s	remaining: 28m 23s
165:	learn: 0.4749249	total: 5m 38s	remaining: 28m 21s
166:	learn: 0.4739082	total: 5m 40s	remaining: 28m 20s
167:	learn: 0.4729165	total: 5m 43s	remaining: 28m 18s
168:	learn: 0.4721181	total: 5m 45s	remaining: 28m 17s
169:	learn: 0.4711374	total: 5m 47s	remaining: 28m 16s
170:	learn: 0.4703479	total: 5m 49s	remaining: 28m 15s
171:	learn: 0.4696455	total: 5m 51s	remaining: 28m 12s
172:	learn: 0.4688239	total: 5m 53s	remaining: 28m 10s
173:	learn: 0.4679868	total: 5m 55s	remaining: 28m 8s
174:	learn: 0.4667283	total: 5m 57s	remaining: 28m 6s
175:	learn: 0.4659080	total: 5m 59s	remaining: 28m 4s
176:	learn: 0.4648122	total: 6m 1s	remaining: 28m 1s
177:	learn: 0.4641814	total: 6m 3s	remaining: 27m 59s
178:	learn: 0.4635032	total: 6m 5s	remaining: 27m 56s
179:	learn: 0.4629246	total: 6m 7s	remaining: 27m 54s
180:	learn: 0.4621563	total: 6m 9s	remaining: 27m 52s
181:	learn: 0.4612182	total: 6m 11s	remaining: 27m 49s
182:	learn: 0.4604944	total: 6m 13s	remaining: 27m 47s
183:	learn: 0.4597717	total: 6m 15s	remaining: 27m 45s
184:	learn: 0.4593130	total: 6m 17s	remaining: 27m 43s
185:	learn: 0.4583543	total: 6m 19s	remaining: 27m 41s
186:	learn: 0.4573118	total: 6m 21s	remaining: 27m 38s
187:	learn: 0.4565238	total: 6m 23s	remaining: 27m 36s
188:	learn: 0.4557240	total: 6m 25s	remaining: 27m 34s
189:	learn: 0.4545782	total: 6m 27s	remaining: 27m 31s
190:	learn: 0.4538672	total: 6m 29s	remaining: 27m 29s
191:	learn: 0.4532401	total: 6m 31s	remaining: 27m 27s
192:	learn: 0.4523263	total: 6m 33s	remaining: 27m 24s
193:	learn: 0.4515946	total: 6m 35s	remaining: 27m 22s
194:	learn: 0.4502909	total: 6m 37s	remaining: 27m 20s
195:	learn: 0.4494172	total: 6m 39s	remaining: 27m 18s
196:	learn: 0.4485117	total: 6m 41s	remaining: 27m 15s
197:	learn: 0.4475601	total: 6m 43s	remaining: 27m 13s
198:	learn: 0.4466898	total: 6m 45s	remaining: 27m 11s
199:	learn: 0.4460407	total: 6m 47s	remaining: 27m 9s
200:	learn: 0.4449501	total: 6m 49s	remaining: 27m 7s
201:	learn: 0.4439421	total: 6m 51s	remaining: 27m 5s
202:	learn: 0.4429455	total: 6m 53s	remaining: 27m 2s
203:	learn: 0.4422115	total: 6m 55s	remaining: 27m
204:	learn: 0.4414778	total: 6m 57s	remaining: 26m 58s
205:	learn: 0.4406722	total: 6m 59s	remaining: 26m 56s
206:	learn: 0.4401368	total: 7m 1s	remaining: 26m 53s
207:	learn: 0.4394682	total: 7m 3s	remaining: 26m 51s
208:	learn: 0.4387219	total: 7m 5s	remaining: 26m 49s
209:	learn: 0.4381453	total: 7m 7s	remaining: 26m 47s
210:	learn: 0.4371815	total: 7m 9s	remaining: 26m 44s
211:	learn: 0.4364525	total: 7m 11s	remaining: 26m 43s
212:	learn: 0.4355845	total: 7m 13s	remaining: 26m 41s
213:	learn: 0.4347169	total: 7m 15s	remaining: 26m 38s
214:	learn: 0.4336883	total: 7m 17s	remaining: 26m 36s
215:	learn: 0.4326411	total: 7m 19s	remaining: 26m 34s
216:	learn: 0.4320900	total: 7m 21s	remaining: 26m 32s
217:	learn: 0.4308541	total: 7m 23s	remaining: 26m 29s
218:	learn: 0.4301983	total: 7m 25s	remaining: 26m 27s
219:	learn: 0.4292129	total: 7m 27s	remaining: 26m 25s
220:	learn: 0.4284695	total: 7m 29s	remaining: 26m 23s
221:	learn: 0.4276340	total: 7m 31s	remaining: 26m 21s
222:	learn: 0.4266063	total: 7m 33s	remaining: 26m 18s
223:	learn: 0.4258298	total: 7m 35s	remaining: 26m 17s
224:	learn: 0.4247416	total: 7m 37s	remaining: 26m 14s
225:	learn: 0.4237841	total: 7m 39s	remaining: 26m 12s
226:	learn: 0.4230885	total: 7m 41s	remaining: 26m 10s
227:	learn: 0.4223421	total: 7m 43s	remaining: 26m 8s
228:	learn: 0.4216408	total: 7m 45s	remaining: 26m 6s
229:	learn: 0.4210610	total: 7m 47s	remaining: 26m 3s
230:	learn: 0.4207447	total: 7m 49s	remaining: 26m 1s
231:	learn: 0.4201169	total: 7m 51s	remaining: 25m 59s
232:	learn: 0.4193438	total: 7m 53s	remaining: 25m 57s
233:	learn: 0.4184528	total: 7m 55s	remaining: 25m 54s
234:	learn: 0.4178310	total: 7m 56s	remaining: 25m 52s
235:	learn: 0.4169659	total: 7m 59s	remaining: 25m 50s
236:	learn: 0.4162832	total: 8m 1s	remaining: 25m 49s
237:	learn: 0.4156016	total: 8m 3s	remaining: 25m 47s
238:	learn: 0.4146959	total: 8m 5s	remaining: 25m 45s
239:	learn: 0.4139078	total: 8m 7s	remaining: 25m 44s
240:	learn: 0.4130172	total: 8m 9s	remaining: 25m 42s
241:	learn: 0.4121618	total: 8m 11s	remaining: 25m 40s
242:	learn: 0.4115824	total: 8m 14s	remaining: 25m 39s
243:	learn: 0.4106488	total: 8m 16s	remaining: 25m 37s
244:	learn: 0.4100077	total: 8m 18s	remaining: 25m 35s
245:	learn: 0.4090116	total: 8m 20s	remaining: 25m 34s
246:	learn: 0.4082499	total: 8m 23s	remaining: 25m 33s
247:	learn: 0.4076680	total: 8m 25s	remaining: 25m 31s
248:	learn: 0.4068077	total: 8m 27s	remaining: 25m 30s
249:	learn: 0.4060689	total: 8m 29s	remaining: 25m 28s
250:	learn: 0.4056024	total: 8m 31s	remaining: 25m 27s
251:	learn: 0.4049962	total: 8m 33s	remaining: 25m 25s
252:	learn: 0.4042878	total: 8m 36s	remaining: 25m 23s
253:	learn: 0.4035435	total: 8m 38s	remaining: 25m 23s
254:	learn: 0.4028543	total: 8m 41s	remaining: 25m 22s
255:	learn: 0.4022138	total: 8m 43s	remaining: 25m 20s
256:	learn: 0.4014006	total: 8m 45s	remaining: 25m 18s
257:	learn: 0.4007200	total: 8m 47s	remaining: 25m 16s
258:	learn: 0.3998290	total: 8m 49s	remaining: 25m 14s
259:	learn: 0.3991930	total: 8m 51s	remaining: 25m 11s
260:	learn: 0.3985242	total: 8m 53s	remaining: 25m 9s
261:	learn: 0.3978584	total: 8m 55s	remaining: 25m 7s
262:	learn: 0.3972007	total: 8m 57s	remaining: 25m 5s
263:	learn: 0.3964892	total: 8m 59s	remaining: 25m 3s
264:	learn: 0.3957256	total: 9m 1s	remaining: 25m 1s
265:	learn: 0.3950080	total: 9m 3s	remaining: 24m 59s
266:	learn: 0.3941703	total: 9m 5s	remaining: 24m 57s
267:	learn: 0.3935990	total: 9m 7s	remaining: 24m 56s
268:	learn: 0.3930892	total: 9m 10s	remaining: 24m 54s
269:	learn: 0.3921123	total: 9m 12s	remaining: 24m 52s
270:	learn: 0.3915156	total: 9m 14s	remaining: 24m 50s
271:	learn: 0.3909610	total: 9m 16s	remaining: 24m 48s
272:	learn: 0.3904142	total: 9m 18s	remaining: 24m 46s
273:	learn: 0.3898469	total: 9m 20s	remaining: 24m 43s
274:	learn: 0.3894291	total: 9m 22s	remaining: 24m 41s
275:	learn: 0.3887564	total: 9m 24s	remaining: 24m 39s
276:	learn: 0.3883086	total: 9m 26s	remaining: 24m 37s
277:	learn: 0.3877677	total: 9m 28s	remaining: 24m 35s
278:	learn: 0.3871808	total: 9m 30s	remaining: 24m 33s
279:	learn: 0.3862937	total: 9m 32s	remaining: 24m 31s
280:	learn: 0.3854391	total: 9m 34s	remaining: 24m 29s
281:	learn: 0.3846034	total: 9m 36s	remaining: 24m 27s
282:	learn: 0.3838670	total: 9m 38s	remaining: 24m 24s
283:	learn: 0.3830576	total: 9m 40s	remaining: 24m 22s
284:	learn: 0.3824394	total: 9m 42s	remaining: 24m 20s
285:	learn: 0.3820141	total: 9m 44s	remaining: 24m 18s
286:	learn: 0.3812910	total: 9m 46s	remaining: 24m 16s
287:	learn: 0.3807459	total: 9m 48s	remaining: 24m 14s
288:	learn: 0.3802419	total: 9m 50s	remaining: 24m 11s
289:	learn: 0.3796287	total: 9m 52s	remaining: 24m 9s
290:	learn: 0.3789019	total: 9m 54s	remaining: 24m 7s
291:	learn: 0.3781234	total: 9m 56s	remaining: 24m 5s
292:	learn: 0.3776292	total: 9m 58s	remaining: 24m 2s
293:	learn: 0.3768770	total: 9m 59s	remaining: 24m
294:	learn: 0.3761661	total: 10m 1s	remaining: 23m 58s
295:	learn: 0.3755846	total: 10m 3s	remaining: 23m 56s
296:	learn: 0.3748439	total: 10m 5s	remaining: 23m 54s
297:	learn: 0.3740496	total: 10m 7s	remaining: 23m 52s
298:	learn: 0.3735106	total: 10m 9s	remaining: 23m 50s
299:	learn: 0.3729727	total: 10m 12s	remaining: 23m 48s
300:	learn: 0.3726169	total: 10m 14s	remaining: 23m 46s
301:	learn: 0.3720032	total: 10m 16s	remaining: 23m 44s
302:	learn: 0.3714874	total: 10m 18s	remaining: 23m 42s
303:	learn: 0.3706404	total: 10m 20s	remaining: 23m 40s
304:	learn: 0.3700431	total: 10m 22s	remaining: 23m 38s
305:	learn: 0.3694138	total: 10m 24s	remaining: 23m 36s
306:	learn: 0.3686391	total: 10m 26s	remaining: 23m 34s
307:	learn: 0.3679145	total: 10m 28s	remaining: 23m 32s
308:	learn: 0.3671612	total: 10m 30s	remaining: 23m 30s
309:	learn: 0.3666036	total: 10m 33s	remaining: 23m 29s
310:	learn: 0.3659416	total: 10m 35s	remaining: 23m 27s
311:	learn: 0.3651328	total: 10m 37s	remaining: 23m 26s
312:	learn: 0.3642412	total: 10m 40s	remaining: 23m 24s
313:	learn: 0.3636144	total: 10m 42s	remaining: 23m 23s
314:	learn: 0.3630370	total: 10m 44s	remaining: 23m 21s
315:	learn: 0.3626211	total: 10m 46s	remaining: 23m 19s
316:	learn: 0.3620405	total: 10m 48s	remaining: 23m 17s
317:	learn: 0.3613183	total: 10m 50s	remaining: 23m 16s
318:	learn: 0.3607123	total: 10m 52s	remaining: 23m 13s
319:	learn: 0.3602249	total: 10m 54s	remaining: 23m 11s
320:	learn: 0.3595483	total: 10m 56s	remaining: 23m 9s
321:	learn: 0.3590137	total: 10m 58s	remaining: 23m 7s
322:	learn: 0.3582403	total: 11m	remaining: 23m 5s
323:	learn: 0.3577758	total: 11m 2s	remaining: 23m 2s
324:	learn: 0.3571194	total: 11m 4s	remaining: 23m
325:	learn: 0.3566628	total: 11m 6s	remaining: 22m 58s
326:	learn: 0.3558708	total: 11m 8s	remaining: 22m 56s
327:	learn: 0.3554022	total: 11m 10s	remaining: 22m 54s
328:	learn: 0.3549997	total: 11m 12s	remaining: 22m 52s
329:	learn: 0.3542648	total: 11m 14s	remaining: 22m 50s
330:	learn: 0.3537610	total: 11m 16s	remaining: 22m 48s
331:	learn: 0.3532995	total: 11m 18s	remaining: 22m 45s
332:	learn: 0.3525096	total: 11m 20s	remaining: 22m 43s
333:	learn: 0.3516537	total: 11m 22s	remaining: 22m 41s
334:	learn: 0.3509773	total: 11m 24s	remaining: 22m 39s
335:	learn: 0.3503628	total: 11m 26s	remaining: 22m 37s
336:	learn: 0.3494757	total: 11m 28s	remaining: 22m 34s
337:	learn: 0.3485044	total: 11m 30s	remaining: 22m 32s
338:	learn: 0.3480746	total: 11m 32s	remaining: 22m 30s
339:	learn: 0.3476031	total: 11m 34s	remaining: 22m 28s
340:	learn: 0.3465568	total: 11m 36s	remaining: 22m 26s
341:	learn: 0.3458330	total: 11m 38s	remaining: 22m 24s
342:	learn: 0.3453236	total: 11m 40s	remaining: 22m 22s
343:	learn: 0.3446301	total: 11m 42s	remaining: 22m 20s
344:	learn: 0.3442361	total: 11m 44s	remaining: 22m 18s
345:	learn: 0.3439699	total: 11m 46s	remaining: 22m 15s
346:	learn: 0.3431834	total: 11m 48s	remaining: 22m 13s
347:	learn: 0.3422972	total: 11m 50s	remaining: 22m 11s
348:	learn: 0.3418286	total: 11m 52s	remaining: 22m 9s
349:	learn: 0.3411154	total: 11m 54s	remaining: 22m 7s
350:	learn: 0.3405974	total: 11m 56s	remaining: 22m 5s
351:	learn: 0.3399463	total: 11m 58s	remaining: 22m 3s
352:	learn: 0.3394519	total: 12m	remaining: 22m
353:	learn: 0.3387807	total: 12m 2s	remaining: 21m 58s
354:	learn: 0.3382986	total: 12m 4s	remaining: 21m 56s
355:	learn: 0.3377963	total: 12m 6s	remaining: 21m 54s
356:	learn: 0.3374536	total: 12m 8s	remaining: 21m 52s
357:	learn: 0.3368046	total: 12m 10s	remaining: 21m 50s
358:	learn: 0.3359772	total: 12m 12s	remaining: 21m 48s
359:	learn: 0.3354680	total: 12m 14s	remaining: 21m 45s
360:	learn: 0.3350645	total: 12m 16s	remaining: 21m 43s
361:	learn: 0.3346687	total: 12m 18s	remaining: 21m 41s
362:	learn: 0.3335494	total: 12m 20s	remaining: 21m 39s
363:	learn: 0.3328100	total: 12m 22s	remaining: 21m 37s
364:	learn: 0.3322556	total: 12m 24s	remaining: 21m 35s
365:	learn: 0.3316351	total: 12m 26s	remaining: 21m 33s
366:	learn: 0.3311282	total: 12m 28s	remaining: 21m 30s

In [77]:
X_meta_val_2 = np.column_stack([
    lr_pipeline_2.predict_proba(X_val_Sex_F)[:, 1],
    lgb_model_2.predict_proba(X_val_Sex_F)[:, 1],
    cat_model_2.predict_proba(X_val_Sex_F)[:, 1]
])

In [78]:
oof_meta_Sex_F = meta_model_2.predict_proba(X_meta_train_2)[:, 1]

In [79]:
print("Stacking ROC-AUC:", roc_auc_score(y_train_Sex_F_, oof_meta_Sex_F))

Stacking ROC-AUC: 0.759379732525649

In [80]:
metrics_meta_ADHD = get_metrics_classification(y_test=y_val_ADHD,
                               y_pred=meta_model_1.predict(X_meta_val_1),
                               y_score=meta_model_1.predict_proba(X_meta_val_1),
                               name='Meta_LR_ADHD')

metrics_meta_ADHD

          model  Accuracy   ROC_AUC  Precision    Recall        f1   Logloss
0  Meta_LR_ADHD  0.688742  0.697556     0.6875  0.926316  0.789238  0.597453

In [81]:
metrics_meta_Sex_F = get_metrics_classification(y_test=y_val_Sex_F,
                               y_pred=meta_model_2.predict(X_meta_val_2),
                               y_score=meta_model_2.predict_proba(X_meta_val_2),
                               name='Meta_LR_Sex_F')

metrics_meta_Sex_F

           model  Accuracy   ROC_AUC  Precision    Recall        f1   Logloss
0  Meta_LR_Sex_F  0.741722  0.779878   0.702703  0.481481  0.571429  0.546335

In [82]:
Full_metrics_ADHD = pd.concat([metrics_ADHD, metrics_optuna_ADHD, metrics_meta_ADHD], axis = 0, ignore_index = True)

round(Full_metrics_ADHD.set_index('model'), 3)

,Accuracy,ROC_AUC,Precision,Recall,f1,Logloss
model,,,,,,
LogisticRegression_Baseline_ADHD,0.636,0.585,0.727,0.762,0.744,1.400
LightGBM_eval_Baseline_ADHD,0.702,0.788,0.698,0.926,0.796,0.565
CatBoost_eval_Baseline_ADHD,0.689,0.743,0.682,0.947,0.793,0.633
LogisticRegression_Optuna_ADHD,0.483,0.578,0.721,0.419,0.530,0.739
LightGBM_Optuna_ADHD,0.689,0.733,0.671,0.989,0.800,0.991
LightGBM_Optuna_ADHD,0.689,0.693,0.671,0.989,0.800,0.616
CatBoost_Optuna_ADHD,0.656,0.669,0.650,0.979,0.782,0.624
Meta_LR_ADHD,0.689,0.698,0.688,0.926,0.789,0.597

In [83]:
Full_metrics_Sex_F = pd.concat([metrics_Sex_F, metrics_optuna_Sex_F, metrics_meta_Sex_F], axis = 0, ignore_index = True)

round(Full_metrics_Sex_F.set_index('model'), 4)

,Accuracy,ROC_AUC,Precision,Recall,f1,Logloss
model,,,,,,
LogisticRegression_Baseline_Sex_F,0.7086,0.7238,0.5405,0.4255,0.4762,0.9901
LightGBM_Baseline_Sex_F,0.6689,0.7234,0.6250,0.1852,0.2857,0.6430
CatBoost_Baseline_Sex_F,0.6755,0.7564,0.7778,0.1296,0.2222,0.5729
LogisticRegression_Optuna_Sex_F,0.6424,0.7249,0.0000,0.0000,0.0000,0.6165
LightGBM_Optuna_Sex_F,0.7020,0.6762,0.7143,0.2778,0.4000,0.6135
CatBoost_Optuna_Sex_F,0.6623,0.7331,0.7143,0.0926,0.1639,0.5908
Meta_LR_Sex_F,0.7417,0.7799,0.7027,0.4815,0.5714,0.5463

In [86]:
from sklearn.base import clone

In [92]:
def evaluate_stacking_cv(models,
                        X,
                        y,
                        n_folds=5,
                        inner_folds=5,
                        random_state=10):
    
    outer_cv = StratifiedKFold(n_splits=n_folds,
                                shuffle=True,
                                random_state=random_state)

    scores = []

    for fold, (train_idx, val_idx) in enumerate(outer_cv.split(X, y), 1):

        print(f"\nFold {fold}")

        # =========================
        # OUTER TRAIN / VALIDATION
        # =========================

        X_train = X.iloc[train_idx]
        X_val = X.iloc[val_idx]

        y_train = y.iloc[train_idx]
        y_val = y.iloc[val_idx]

        # =========================
        # INNER CV
        # Получаем OOF predictions
        # для meta-model
        # =========================

        inner_cv = StratifiedKFold(n_splits=inner_folds,
                                   shuffle=True,
                                   random_state=random_state)

        oof_train = np.zeros((len(X_train), len(models)))

        for inner_train_idx, inner_val_idx in inner_cv.split(X_train, y_train):

            X_inner_train = X_train.iloc[inner_train_idx]
            X_inner_val = X_train.iloc[inner_val_idx]

            y_inner_train = y_train.iloc[inner_train_idx]
            y_inner_val = y_train.iloc[inner_val_idx]

            for model_idx, model in enumerate(models):

                model_inner = clone(model)

                model_inner.fit(X_inner_train, y_inner_train)

                oof_train[inner_val_idx, model_idx] = model_inner.predict_proba(X_inner_val)[:, 1]

        # =========================
        # META-MODEL
        # =========================

        meta_model = LogisticRegression(max_iter=1000)

        meta_model.fit(oof_train, y_train)

        # =========================
        # ОБУЧАЕМ BASE MODELS
        # НА ВСЁМ OUTER TRAIN
        # =========================

        meta_val = np.zeros((len(X_val), len(models)))

        for model_idx, model in enumerate(models):

            model_outer = clone(model)

            model_outer.fit(X_train, y_train)

            meta_val[:,model_idx] = model_outer.predict_proba(X_val)[:, 1]

        # =========================
        # FINAL STACKING PREDICTION
        # =========================

        y_pred_proba = meta_model.predict_proba(meta_val)[:, 1]

        score = roc_auc_score(y_val, y_pred_proba)

        scores.append(score)

        print(f"Fold {fold}: ROC-AUC = {score:.4f}")

    # =========================
    # FINAL RESULTS
    # =========================

    mean_score = np.mean(scores)
    std_score = np.std(scores)

    print(f"\nMean ROC-AUC: {mean_score:.4f}")

    print(f"Std: {std_score:.4f}")

    return mean_score, std_score

In [87]:
models_ADHD = [lr_pipeline_1,
               lgb_model_1,
               cat_model_1]

In [93]:
stack_mean_ADHD, stack_std_ADHD = evaluate_stacking_cv(
    models=models_ADHD,
    X=X_train_ADHD_,
    y=y_train_ADHD_,
    n_folds=5,
    inner_folds=5,
    random_state=10
)

Fold 1
Fold 1: ROC-AUC = 0.6595

Fold 2
Fold 2: ROC-AUC = 0.6678

Fold 3
Fold 3: ROC-AUC = 0.7165

Fold 4
Fold 4: ROC-AUC = 0.7470

Fold 5
Fold 5: ROC-AUC = 0.6119

Mean ROC-AUC: 0.6805
Std: 0.0470

In [88]:
models_Sex_F = [lr_pipeline_2,
                lgb_model_2,
                cat_model_2]

In [94]:
stack_mean_Sex_F, stack_std_Sex_F = evaluate_stacking_cv(
    models=models_Sex_F,
    X=X_train_Sex_F_,
    y=y_train_Sex_F_,
    n_folds=5,
    inner_folds=5,
    random_state=10
)

Fold 1
Learning rate set to 0.007696
0:	learn: 0.6908162	total: 2.89s	remaining: 48m 10s
1:	learn: 0.6890553	total: 4.95s	remaining: 41m 9s
2:	learn: 0.6877868	total: 7.05s	remaining: 39m 2s
3:	learn: 0.6856873	total: 9.05s	remaining: 37m 33s
4:	learn: 0.6835897	total: 11.1s	remaining: 36m 45s
5:	learn: 0.6821185	total: 13.1s	remaining: 36m 11s
6:	learn: 0.6803981	total: 15.1s	remaining: 35m 41s
7:	learn: 0.6783302	total: 17.1s	remaining: 35m 21s
8:	learn: 0.6763381	total: 19.1s	remaining: 35m 5s
9:	learn: 0.6746345	total: 21.1s	remaining: 34m 51s
10:	learn: 0.6725994	total: 23.1s	remaining: 34m 40s
11:	learn: 0.6709938	total: 25.1s	remaining: 34m 25s
12:	learn: 0.6690600	total: 27.1s	remaining: 34m 17s
13:	learn: 0.6675179	total: 29.2s	remaining: 34m 15s
14:	learn: 0.6658758	total: 31.3s	remaining: 34m 15s
15:	learn: 0.6637911	total: 33.5s	remaining: 34m 19s
16:	learn: 0.6627425	total: 35.5s	remaining: 34m 15s
17:	learn: 0.6609584	total: 37.8s	remaining: 34m 20s
18:	learn: 0.6592822	total: 40s	remaining: 34m 25s
19:	learn: 0.6570450	total: 42.3s	remaining: 34m 30s
20:	learn: 0.6545231	total: 44.4s	remaining: 34m 27s
21:	learn: 0.6525773	total: 46.6s	remaining: 34m 30s
22:	learn: 0.6510107	total: 48.6s	remaining: 34m 23s
23:	learn: 0.6491991	total: 50.8s	remaining: 34m 25s
24:	learn: 0.6470836	total: 52.8s	remaining: 34m 21s
25:	learn: 0.6455285	total: 54.9s	remaining: 34m 18s
26:	learn: 0.6439116	total: 57.1s	remaining: 34m 16s
27:	learn: 0.6421838	total: 59.3s	remaining: 34m 18s
28:	learn: 0.6403553	total: 1m 1s	remaining: 34m 17s
29:	learn: 0.6384808	total: 1m 3s	remaining: 34m 15s
30:	learn: 0.6369649	total: 1m 5s	remaining: 34m 12s
31:	learn: 0.6350020	total: 1m 7s	remaining: 34m 13s
32:	learn: 0.6335431	total: 1m 10s	remaining: 34m 13s
33:	learn: 0.6320845	total: 1m 12s	remaining: 34m 19s
34:	learn: 0.6309262	total: 1m 14s	remaining: 34m 14s
35:	learn: 0.6292344	total: 1m 16s	remaining: 34m 9s
36:	learn: 0.6272226	total: 1m 18s	remaining: 34m 9s
37:	learn: 0.6255532	total: 1m 20s	remaining: 34m 5s
38:	learn: 0.6232512	total: 1m 22s	remaining: 34m 1s
39:	learn: 0.6212958	total: 1m 24s	remaining: 33m 57s
40:	learn: 0.6192669	total: 1m 26s	remaining: 33m 52s
41:	learn: 0.6179463	total: 1m 29s	remaining: 33m 54s
42:	learn: 0.6163226	total: 1m 31s	remaining: 33m 49s
43:	learn: 0.6151330	total: 1m 33s	remaining: 33m 43s
44:	learn: 0.6131414	total: 1m 35s	remaining: 33m 39s
45:	learn: 0.6112038	total: 1m 37s	remaining: 33m 36s
46:	learn: 0.6098562	total: 1m 39s	remaining: 33m 32s
47:	learn: 0.6082037	total: 1m 41s	remaining: 33m 28s
48:	learn: 0.6062638	total: 1m 43s	remaining: 33m 23s
49:	learn: 0.6048851	total: 1m 45s	remaining: 33m 20s
50:	learn: 0.6036592	total: 1m 47s	remaining: 33m 17s
51:	learn: 0.6022336	total: 1m 49s	remaining: 33m 14s
52:	learn: 0.6004819	total: 1m 51s	remaining: 33m 11s
53:	learn: 0.5987282	total: 1m 53s	remaining: 33m 8s
54:	learn: 0.5973434	total: 1m 55s	remaining: 33m 4s
55:	learn: 0.5951181	total: 1m 57s	remaining: 33m
56:	learn: 0.5935823	total: 1m 59s	remaining: 32m 57s
57:	learn: 0.5918962	total: 2m 1s	remaining: 32m 54s
58:	learn: 0.5903794	total: 2m 3s	remaining: 32m 51s
59:	learn: 0.5889505	total: 2m 5s	remaining: 32m 48s
60:	learn: 0.5873514	total: 2m 7s	remaining: 32m 45s
61:	learn: 0.5857472	total: 2m 9s	remaining: 32m 41s
62:	learn: 0.5845276	total: 2m 11s	remaining: 32m 38s
63:	learn: 0.5830852	total: 2m 13s	remaining: 32m 35s
64:	learn: 0.5818562	total: 2m 15s	remaining: 32m 31s
65:	learn: 0.5804760	total: 2m 17s	remaining: 32m 29s
66:	learn: 0.5791239	total: 2m 19s	remaining: 32m 27s
67:	learn: 0.5781332	total: 2m 21s	remaining: 32m 24s
68:	learn: 0.5768947	total: 2m 23s	remaining: 32m 21s
69:	learn: 0.5754145	total: 2m 25s	remaining: 32m 18s
70:	learn: 0.5739597	total: 2m 27s	remaining: 32m 15s
71:	learn: 0.5726885	total: 2m 29s	remaining: 32m 11s
72:	learn: 0.5714659	total: 2m 31s	remaining: 32m 8s
73:	learn: 0.5705800	total: 2m 33s	remaining: 32m 4s
74:	learn: 0.5694950	total: 2m 35s	remaining: 32m 2s
75:	learn: 0.5681519	total: 2m 37s	remaining: 32m
76:	learn: 0.5670487	total: 2m 39s	remaining: 31m 57s
77:	learn: 0.5655862	total: 2m 42s	remaining: 31m 54s
78:	learn: 0.5640201	total: 2m 44s	remaining: 31m 54s
79:	learn: 0.5626293	total: 2m 46s	remaining: 31m 53s
80:	learn: 0.5613222	total: 2m 48s	remaining: 31m 52s
81:	learn: 0.5594442	total: 2m 50s	remaining: 31m 50s
82:	learn: 0.5579919	total: 2m 52s	remaining: 31m 50s
83:	learn: 0.5568956	total: 2m 55s	remaining: 31m 49s
84:	learn: 0.5554519	total: 2m 57s	remaining: 31m 51s
85:	learn: 0.5542105	total: 2m 59s	remaining: 31m 50s
86:	learn: 0.5528147	total: 3m 1s	remaining: 31m 49s
87:	learn: 0.5508904	total: 3m 4s	remaining: 31m 49s
88:	learn: 0.5497128	total: 3m 6s	remaining: 31m 49s
89:	learn: 0.5481312	total: 3m 8s	remaining: 31m 48s
90:	learn: 0.5466957	total: 3m 10s	remaining: 31m 46s
91:	learn: 0.5451823	total: 3m 13s	remaining: 31m 46s
92:	learn: 0.5440299	total: 3m 15s	remaining: 31m 44s
93:	learn: 0.5427082	total: 3m 17s	remaining: 31m 44s
94:	learn: 0.5414903	total: 3m 19s	remaining: 31m 43s
95:	learn: 0.5398469	total: 3m 21s	remaining: 31m 41s
96:	learn: 0.5389985	total: 3m 23s	remaining: 31m 38s
97:	learn: 0.5372587	total: 3m 25s	remaining: 31m 35s
98:	learn: 0.5360626	total: 3m 28s	remaining: 31m 33s
99:	learn: 0.5348331	total: 3m 30s	remaining: 31m 30s
100:	learn: 0.5334234	total: 3m 32s	remaining: 31m 27s
101:	learn: 0.5323591	total: 3m 34s	remaining: 31m 25s
102:	learn: 0.5306478	total: 3m 36s	remaining: 31m 22s
103:	learn: 0.5297957	total: 3m 38s	remaining: 31m 19s
104:	learn: 0.5282662	total: 3m 40s	remaining: 31m 17s
105:	learn: 0.5268425	total: 3m 42s	remaining: 31m 14s
106:	learn: 0.5253917	total: 3m 44s	remaining: 31m 11s
107:	learn: 0.5241590	total: 3m 46s	remaining: 31m 8s
108:	learn: 0.5230741	total: 3m 48s	remaining: 31m 5s
109:	learn: 0.5218692	total: 3m 50s	remaining: 31m 3s
110:	learn: 0.5209159	total: 3m 52s	remaining: 31m
111:	learn: 0.5200392	total: 3m 54s	remaining: 30m 57s
112:	learn: 0.5189746	total: 3m 56s	remaining: 30m 54s
113:	learn: 0.5176931	total: 3m 58s	remaining: 30m 52s
114:	learn: 0.5168285	total: 4m	remaining: 30m 49s
115:	learn: 0.5161365	total: 4m 2s	remaining: 30m 46s
116:	learn: 0.5151942	total: 4m 4s	remaining: 30m 43s
117:	learn: 0.5143706	total: 4m 6s	remaining: 30m 40s
118:	learn: 0.5133971	total: 4m 8s	remaining: 30m 37s
119:	learn: 0.5118953	total: 4m 10s	remaining: 30m 35s
120:	learn: 0.5108628	total: 4m 12s	remaining: 30m 33s
121:	learn: 0.5098671	total: 4m 14s	remaining: 30m 30s
122:	learn: 0.5084077	total: 4m 16s	remaining: 30m 28s
123:	learn: 0.5072432	total: 4m 18s	remaining: 30m 25s
124:	learn: 0.5057066	total: 4m 20s	remaining: 30m 24s
125:	learn: 0.5040583	total: 4m 22s	remaining: 30m 21s
126:	learn: 0.5031616	total: 4m 24s	remaining: 30m 18s
127:	learn: 0.5019973	total: 4m 26s	remaining: 30m 16s
128:	learn: 0.5004079	total: 4m 28s	remaining: 30m 14s
129:	learn: 0.4991504	total: 4m 30s	remaining: 30m 11s
130:	learn: 0.4981302	total: 4m 32s	remaining: 30m 9s
131:	learn: 0.4972557	total: 4m 34s	remaining: 30m 6s
132:	learn: 0.4964810	total: 4m 36s	remaining: 30m 4s
133:	learn: 0.4954537	total: 4m 38s	remaining: 30m 1s
134:	learn: 0.4943339	total: 4m 40s	remaining: 29m 58s
135:	learn: 0.4934645	total: 4m 42s	remaining: 29m 56s
136:	learn: 0.4921924	total: 4m 44s	remaining: 29m 53s
137:	learn: 0.4912030	total: 4m 46s	remaining: 29m 50s
138:	learn: 0.4904078	total: 4m 48s	remaining: 29m 48s
139:	learn: 0.4889722	total: 4m 50s	remaining: 29m 46s
140:	learn: 0.4875712	total: 4m 52s	remaining: 29m 43s
141:	learn: 0.4866156	total: 4m 54s	remaining: 29m 40s
142:	learn: 0.4854440	total: 4m 56s	remaining: 29m 38s
143:	learn: 0.4836796	total: 4m 58s	remaining: 29m 35s
144:	learn: 0.4828155	total: 5m	remaining: 29m 33s
145:	learn: 0.4818260	total: 5m 2s	remaining: 29m 31s
146:	learn: 0.4809476	total: 5m 4s	remaining: 29m 29s
147:	learn: 0.4802075	total: 5m 7s	remaining: 29m 27s
148:	learn: 0.4791239	total: 5m 9s	remaining: 29m 25s
149:	learn: 0.4776579	total: 5m 11s	remaining: 29m 24s
150:	learn: 0.4765769	total: 5m 13s	remaining: 29m 23s
151:	learn: 0.4752633	total: 5m 15s	remaining: 29m 22s
152:	learn: 0.4741415	total: 5m 18s	remaining: 29m 21s
153:	learn: 0.4729939	total: 5m 20s	remaining: 29m 19s
154:	learn: 0.4720556	total: 5m 22s	remaining: 29m 17s
155:	learn: 0.4709160	total: 5m 24s	remaining: 29m 15s
156:	learn: 0.4697007	total: 5m 26s	remaining: 29m 13s
157:	learn: 0.4686073	total: 5m 28s	remaining: 29m 11s
158:	learn: 0.4674483	total: 5m 30s	remaining: 29m 9s
159:	learn: 0.4657349	total: 5m 32s	remaining: 29m 7s
160:	learn: 0.4646565	total: 5m 35s	remaining: 29m 5s
161:	learn: 0.4638341	total: 5m 37s	remaining: 29m 3s
162:	learn: 0.4627694	total: 5m 39s	remaining: 29m 1s
163:	learn: 0.4615705	total: 5m 41s	remaining: 29m
164:	learn: 0.4604174	total: 5m 43s	remaining: 28m 59s
165:	learn: 0.4596145	total: 5m 45s	remaining: 28m 57s
166:	learn: 0.4586353	total: 5m 47s	remaining: 28m 55s
167:	learn: 0.4574017	total: 5m 50s	remaining: 28m 53s
168:	learn: 0.4562025	total: 5m 52s	remaining: 28m 52s
169:	learn: 0.4551100	total: 5m 54s	remaining: 28m 50s
170:	learn: 0.4539380	total: 5m 56s	remaining: 28m 49s
171:	learn: 0.4531558	total: 5m 58s	remaining: 28m 47s
172:	learn: 0.4519804	total: 6m 1s	remaining: 28m 46s
173:	learn: 0.4507883	total: 6m 3s	remaining: 28m 45s
174:	learn: 0.4501182	total: 6m 5s	remaining: 28m 43s
175:	learn: 0.4490920	total: 6m 7s	remaining: 28m 41s
176:	learn: 0.4482742	total: 6m 9s	remaining: 28m 39s
177:	learn: 0.4472097	total: 6m 11s	remaining: 28m 36s
178:	learn: 0.4465042	total: 6m 13s	remaining: 28m 34s
179:	learn: 0.4454414	total: 6m 15s	remaining: 28m 32s
180:	learn: 0.4447379	total: 6m 17s	remaining: 28m 29s
181:	learn: 0.4435475	total: 6m 19s	remaining: 28m 26s
182:	learn: 0.4426034	total: 6m 21s	remaining: 28m 24s
183:	learn: 0.4413477	total: 6m 23s	remaining: 28m 22s
184:	learn: 0.4399738	total: 6m 25s	remaining: 28m 19s
185:	learn: 0.4390288	total: 6m 27s	remaining: 28m 17s
186:	learn: 0.4384229	total: 6m 29s	remaining: 28m 14s
187:	learn: 0.4375483	total: 6m 31s	remaining: 28m 12s
188:	learn: 0.4364747	total: 6m 33s	remaining: 28m 9s
189:	learn: 0.4356716	total: 6m 35s	remaining: 28m 8s
190:	learn: 0.4343994	total: 6m 38s	remaining: 28m 5s
191:	learn: 0.4334736	total: 6m 40s	remaining: 28m 3s
192:	learn: 0.4323374	total: 6m 42s	remaining: 28m 1s
193:	learn: 0.4315765	total: 6m 44s	remaining: 27m 59s
194:	learn: 0.4306155	total: 6m 46s	remaining: 27m 57s
195:	learn: 0.4298821	total: 6m 48s	remaining: 27m 55s
196:	learn: 0.4288661	total: 6m 50s	remaining: 27m 53s
197:	learn: 0.4282227	total: 6m 52s	remaining: 27m 51s
198:	learn: 0.4273276	total: 6m 54s	remaining: 27m 49s
199:	learn: 0.4266349	total: 6m 57s	remaining: 27m 48s
200:	learn: 0.4258473	total: 6m 59s	remaining: 27m 46s
201:	learn: 0.4246930	total: 7m 1s	remaining: 27m 45s
202:	learn: 0.4233063	total: 7m 3s	remaining: 27m 43s
203:	learn: 0.4228190	total: 7m 5s	remaining: 27m 42s
204:	learn: 0.4220267	total: 7m 8s	remaining: 27m 40s
205:	learn: 0.4211798	total: 7m 10s	remaining: 27m 39s
206:	learn: 0.4201150	total: 7m 12s	remaining: 27m 37s
207:	learn: 0.4189692	total: 7m 14s	remaining: 27m 35s
208:	learn: 0.4179649	total: 7m 16s	remaining: 27m 33s
209:	learn: 0.4169981	total: 7m 19s	remaining: 27m 32s
210:	learn: 0.4160181	total: 7m 21s	remaining: 27m 30s
211:	learn: 0.4154191	total: 7m 23s	remaining: 27m 28s
212:	learn: 0.4143487	total: 7m 25s	remaining: 27m 26s
213:	learn: 0.4134836	total: 7m 27s	remaining: 27m 24s
214:	learn: 0.4128545	total: 7m 29s	remaining: 27m 21s
215:	learn: 0.4122572	total: 7m 31s	remaining: 27m 19s
216:	learn: 0.4117907	total: 7m 33s	remaining: 27m 17s
217:	learn: 0.4112471	total: 7m 35s	remaining: 27m 14s
218:	learn: 0.4103717	total: 7m 37s	remaining: 27m 12s
219:	learn: 0.4095167	total: 7m 39s	remaining: 27m 9s
220:	learn: 0.4085079	total: 7m 41s	remaining: 27m 7s
221:	learn: 0.4076753	total: 7m 43s	remaining: 27m 5s
222:	learn: 0.4066913	total: 7m 45s	remaining: 27m 2s
223:	learn: 0.4058171	total: 7m 47s	remaining: 27m
224:	learn: 0.4051347	total: 7m 49s	remaining: 26m 58s
225:	learn: 0.4042652	total: 7m 51s	remaining: 26m 55s
226:	learn: 0.4031689	total: 7m 53s	remaining: 26m 53s
227:	learn: 0.4024589	total: 7m 55s	remaining: 26m 51s
228:	learn: 0.4014250	total: 7m 57s	remaining: 26m 49s
229:	learn: 0.4007384	total: 7m 59s	remaining: 26m 46s
230:	learn: 0.4001205	total: 8m 1s	remaining: 26m 44s
231:	learn: 0.3995372	total: 8m 3s	remaining: 26m 41s
232:	learn: 0.3987010	total: 8m 5s	remaining: 26m 39s
233:	learn: 0.3977815	total: 8m 8s	remaining: 26m 37s
234:	learn: 0.3966512	total: 8m 10s	remaining: 26m 35s
235:	learn: 0.3957743	total: 8m 12s	remaining: 26m 32s
236:	learn: 0.3947160	total: 8m 14s	remaining: 26m 30s
237:	learn: 0.3942067	total: 8m 16s	remaining: 26m 28s
238:	learn: 0.3935478	total: 8m 18s	remaining: 26m 26s
239:	learn: 0.3926208	total: 8m 20s	remaining: 26m 23s
240:	learn: 0.3918712	total: 8m 22s	remaining: 26m 21s
241:	learn: 0.3908730	total: 8m 24s	remaining: 26m 19s
242:	learn: 0.3899405	total: 8m 26s	remaining: 26m 16s
243:	learn: 0.3889702	total: 8m 29s	remaining: 26m 17s
244:	learn: 0.3879889	total: 8m 31s	remaining: 26m 15s
245:	learn: 0.3868272	total: 8m 33s	remaining: 26m 12s
246:	learn: 0.3860356	total: 8m 35s	remaining: 26m 10s
247:	learn: 0.3849525	total: 8m 37s	remaining: 26m 8s
248:	learn: 0.3843822	total: 8m 39s	remaining: 26m 6s
249:	learn: 0.3834664	total: 8m 41s	remaining: 26m 4s
250:	learn: 0.3827032	total: 8m 43s	remaining: 26m 2s
251:	learn: 0.3820318	total: 8m 45s	remaining: 25m 59s
252:	learn: 0.3811003	total: 8m 47s	remaining: 25m 57s
253:	learn: 0.3802052	total: 8m 49s	remaining: 25m 55s
254:	learn: 0.3794658	total: 8m 51s	remaining: 25m 52s
255:	learn: 0.3781646	total: 8m 53s	remaining: 25m 50s
256:	learn: 0.3774360	total: 8m 55s	remaining: 25m 48s
257:	learn: 0.3768542	total: 8m 57s	remaining: 25m 46s
258:	learn: 0.3762633	total: 8m 59s	remaining: 25m 43s
259:	learn: 0.3755868	total: 9m 1s	remaining: 25m 41s
260:	learn: 0.3751376	total: 9m 3s	remaining: 25m 39s
261:	learn: 0.3739794	total: 9m 5s	remaining: 25m 37s
262:	learn: 0.3733906	total: 9m 7s	remaining: 25m 34s
263:	learn: 0.3728602	total: 9m 9s	remaining: 25m 32s
264:	learn: 0.3721089	total: 9m 11s	remaining: 25m 30s
265:	learn: 0.3715790	total: 9m 13s	remaining: 25m 28s
266:	learn: 0.3709911	total: 9m 15s	remaining: 25m 25s
267:	learn: 0.3702681	total: 9m 17s	remaining: 25m 23s
268:	learn: 0.3696088	total: 9m 19s	remaining: 25m 20s
269:	learn: 0.3689073	total: 9m 21s	remaining: 25m 18s
270:	learn: 0.3680617	total: 9m 23s	remaining: 25m 16s
271:	learn: 0.3672468	total: 9m 25s	remaining: 25m 13s
272:	learn: 0.3660175	total: 9m 27s	remaining: 25m 11s
273:	learn: 0.3651259	total: 9m 29s	remaining: 25m 9s
274:	learn: 0.3645713	total: 9m 31s	remaining: 25m 7s
275:	learn: 0.3639653	total: 9m 33s	remaining: 25m 4s
276:	learn: 0.3632988	total: 9m 35s	remaining: 25m 2s
277:	learn: 0.3628286	total: 9m 37s	remaining: 25m
278:	learn: 0.3620554	total: 9m 39s	remaining: 24m 58s
279:	learn: 0.3613784	total: 9m 42s	remaining: 24m 56s
280:	learn: 0.3606449	total: 9m 44s	remaining: 24m 55s
281:	learn: 0.3600801	total: 9m 46s	remaining: 24m 53s
282:	learn: 0.3595664	total: 9m 48s	remaining: 24m 52s
283:	learn: 0.3587918	total: 9m 51s	remaining: 24m 50s
284:	learn: 0.3580311	total: 9m 53s	remaining: 24m 48s
285:	learn: 0.3571460	total: 9m 55s	remaining: 24m 46s
286:	learn: 0.3565487	total: 9m 57s	remaining: 24m 44s
287:	learn: 0.3560304	total: 9m 59s	remaining: 24m 42s
288:	learn: 0.3552155	total: 10m 1s	remaining: 24m 40s
289:	learn: 0.3547375	total: 10m 3s	remaining: 24m 37s
290:	learn: 0.3541133	total: 10m 5s	remaining: 24m 35s
291:	learn: 0.3534229	total: 10m 7s	remaining: 24m 33s
292:	learn: 0.3525134	total: 10m 9s	remaining: 24m 31s
293:	learn: 0.3517610	total: 10m 11s	remaining: 24m 29s
294:	learn: 0.3510246	total: 10m 13s	remaining: 24m 27s
295:	learn: 0.3504583	total: 10m 15s	remaining: 24m 24s
296:	learn: 0.3498239	total: 10m 17s	remaining: 24m 22s
297:	learn: 0.3489802	total: 10m 19s	remaining: 24m 20s
298:	learn: 0.3483502	total: 10m 22s	remaining: 24m 18s
299:	learn: 0.3475081	total: 10m 24s	remaining: 24m 16s
300:	learn: 0.3469687	total: 10m 26s	remaining: 24m 14s
301:	learn: 0.3462553	total: 10m 28s	remaining: 24m 12s
302:	learn: 0.3454320	total: 10m 30s	remaining: 24m 9s
303:	learn: 0.3446612	total: 10m 32s	remaining: 24m 7s
304:	learn: 0.3439761	total: 10m 34s	remaining: 24m 5s
305:	learn: 0.3432022	total: 10m 36s	remaining: 24m 3s
306:	learn: 0.3426944	total: 10m 38s	remaining: 24m 1s
307:	learn: 0.3418857	total: 10m 40s	remaining: 23m 59s
308:	learn: 0.3412443	total: 10m 42s	remaining: 23m 57s
309:	learn: 0.3406822	total: 10m 44s	remaining: 23m 55s
310:	learn: 0.3399365	total: 10m 46s	remaining: 23m 53s
311:	learn: 0.3392659	total: 10m 49s	remaining: 23m 51s
312:	learn: 0.3385366	total: 10m 51s	remaining: 23m 49s
313:	learn: 0.3379662	total: 10m 53s	remaining: 23m 46s
314:	learn: 0.3371880	total: 10m 55s	remaining: 23m 44s
315:	learn: 0.3366931	total: 10m 57s	remaining: 23m 42s
316:	learn: 0.3358200	total: 10m 59s	remaining: 23m 40s
317:	learn: 0.3352450	total: 11m 1s	remaining: 23m 38s
318:	learn: 0.3347975	total: 11m 3s	remaining: 23m 36s
319:	learn: 0.3341109	total: 11m 5s	remaining: 23m 34s
320:	learn: 0.3333455	total: 11m 7s	remaining: 23m 32s
321:	learn: 0.3326717	total: 11m 9s	remaining: 23m 30s
322:	learn: 0.3317915	total: 11m 11s	remaining: 23m 27s
323:	learn: 0.3310212	total: 11m 13s	remaining: 23m 25s
324:	learn: 0.3301584	total: 11m 15s	remaining: 23m 23s
325:	learn: 0.3295653	total: 11m 17s	remaining: 23m 21s
326:	learn: 0.3291745	total: 11m 19s	remaining: 23m 19s
327:	learn: 0.3283020	total: 11m 22s	remaining: 23m 17s
328:	learn: 0.3276938	total: 11m 24s	remaining: 23m 15s
329:	learn: 0.3273490	total: 11m 26s	remaining: 23m 13s
330:	learn: 0.3268185	total: 11m 28s	remaining: 23m 10s
331:	learn: 0.3258930	total: 11m 30s	remaining: 23m 8s
332:	learn: 0.3252903	total: 11m 32s	remaining: 23m 6s
333:	learn: 0.3245373	total: 11m 34s	remaining: 23m 4s
334:	learn: 0.3238138	total: 11m 36s	remaining: 23m 2s
335:	learn: 0.3232808	total: 11m 38s	remaining: 23m
336:	learn: 0.3227276	total: 11m 40s	remaining: 22m 57s
337:	learn: 0.3222638	total: 11m 42s	remaining: 22m 55s
338:	learn: 0.3213532	total: 11m 44s	remaining: 22m 53s
339:	learn: 0.3208596	total: 11m 46s	remaining: 22m 51s
340:	learn: 0.3200912	total: 11m 48s	remaining: 22m 49s
341:	learn: 0.3195713	total: 11m 50s	remaining: 22m 47s
342:	learn: 0.3186964	total: 11m 52s	remaining: 22m 44s
343:	learn: 0.3178942	total: 11m 54s	remaining: 22m 42s
344:	learn: 0.3172489	total: 11m 56s	remaining: 22m 40s
345:	learn: 0.3165920	total: 11m 58s	remaining: 22m 38s
346:	learn: 0.3160582	total: 12m	remaining: 22m 36s
347:	learn: 0.3155402	total: 12m 2s	remaining: 22m 34s
348:	learn: 0.3150249	total: 12m 4s	remaining: 22m 31s
349:	learn: 0.3144627	total: 12m 6s	remaining: 22m 29s
350:	learn: 0.3136884	total: 12m 8s	remaining: 22m 27s
351:	learn: 0.3131239	total: 12m 10s	remaining: 22m 25s
352:	learn: 0.3123832	total: 12m 12s	remaining: 22m 23s
353:	learn: 0.3118276	total: 12m 14s	remaining: 22m 20s
354:	learn: 0.3111688	total: 12m 16s	remaining: 22m 18s
355:	learn: 0.3105717	total: 12m 18s	remaining: 22m 16s
356:	learn: 0.3099059	total: 12m 20s	remaining: 22m 14s
357:	learn: 0.3093589	total: 12m 22s	remaining: 22m 12s
358:	learn: 0.3085011	total: 12m 24s	remaining: 22m 10s
359:	learn: 0.3079838	total: 12m 26s	remaining: 22m 7s
360:	learn: 0.3072954	total: 12m 28s	remaining: 22m 5s
361:	learn: 0.3065396	total: 12m 31s	remaining: 22m 3s
362:	learn: 0.3058370	total: 12m 32s	remaining: 22m 1s
363:	learn: 0.3052109	total: 12m 34s	remaining: 21m 59s
364:	learn: 0.3046132	total: 12m 36s	remaining: 21m 56s
365:	learn: 0.3039410	total: 12m 39s	remaining: 21m 54s

In [95]:
cv_models_ADHD.append({'Model_ADHD':'Meta_ADHD',
                               'Mean ROC-AUC':stack_mean_ADHD,
                               'Std':stack_std_ADHD})
cv_models_ADHD_df = pd.DataFrame(cv_models_ADHD)
round(cv_models_ADHD_df.set_index('Model_ADHD'), 3)

                                  Mean ROC-AUC    Std
Model_ADHD
LogisticRegression_baseline_ADHD         0.569  0.032
LogisticRegression_optune_ADHD           0.575  0.028
LightGBM_baseline_ADHD                   0.740  0.018
LightGBM_optune_ADHD                     0.753  0.041
CatBoost_baseline_ADHD                   0.660  0.053
CatBoost_optune_ADHD                     0.679  0.042
Meta_ADHD                                0.681  0.047

In [96]:
cv_models_Sex_F.append({'Model_Sex_F':'Meta_Sex_F',
                               'Mean ROC-AUC':stack_mean_Sex_F,
                               'Std':stack_std_Sex_F})
cv_models_Sex_F_df = pd.DataFrame(cv_models_Sex_F)
round(cv_models_Sex_F_df.set_index('Model_Sex_F'), 3)

                                   Mean ROC-AUC    Std
Model_Sex_F
LogisticRegression_baseline_Sex_F         0.748  0.039
LogisticRegression_optune_Sex_F           0.744  0.030
LightGBM_baseline_Sex_F                   0.666  0.025
LightGBM_optune_Sex_F                     0.705  0.037
CatBoost_baseline_Sex_F                   0.668  0.055
CatBoost_optune_Sex_F                     0.663  0.053
Meta_Sex_F                                0.751  0.030

# Финальные модели

In [98]:
X_meta_test_2 = np.column_stack([
    lr_pipeline_2.predict_proba(X_test_Sex_F)[:, 1],
    lgb_model_2.predict_proba(X_test_Sex_F)[:, 1],
    cat_model_2.predict_proba(X_test_Sex_F)[:, 1]
])

In [99]:
metrics_final = get_metrics_classification(y_test=y_test_ADHD,
                               y_pred=clf_ADHD_lgb.predict(X_test_ADHD),
                               y_score=clf_ADHD_lgb.predict_proba(X_test_ADHD),
                               name='LightGBM_optune_ADHD')
metrics_final = pd.concat([metrics_final,
    get_metrics_classification(y_test=y_test_Sex_F,
                               y_pred=meta_model_2.predict(X_meta_test_2),
                               y_score=meta_model_2.predict_proba(X_meta_test_2),
                               name='Meta_Sex_F')])
round(metrics_final.set_index('model'), 3)

                      Accuracy  ROC_AUC  Precision  Recall     f1  Logloss
model
LightGBM_optune_ADHD     0.746    0.773      0.746   0.964  0.841    0.522
Meta_Sex_F               0.716    0.755      0.579   0.434  0.496    0.553